// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveProducts = `-- name: CountActiveProducts :one
SELECT count(*) FROM products
WHERE status = 'active'
  AND (
    $1::text IS NULL
    OR category_id = (SELECT id FROM categories WHERE slug = $1::text)
  )
  AND (
    $2::text IS NULL
    OR to_tsvector('simple', immutable_unaccent(name || ' ' || description))
       @@ plainto_tsquery('simple', immutable_unaccent($2::text))
  )
`

type CountActiveProductsParams struct {
	CategorySlug *string `json:"categorySlug"`
	Search       *string `json:"search"`
}

// CountActiveProducts is the total for the list envelope — the SAME WHERE as ListActiveProducts (including
// the P1-e @search filter, so the envelope total reflects the SEARCHED set, not the whole catalog), with no
// sort/limit. It runs alongside the list as a second autocommit read; a concurrent catalog write landing
// between the two can skew the total by one. That is cosmetic (a display count that self-heals next
// request) on a made-to-order shop whose catalog rarely mutates, and it is never a money value — so we
// accept it rather than pay for a snapshot transaction (documented on the repo method).
func (q *Queries) CountActiveProducts(ctx context.Context, arg CountActiveProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProducts, arg.CategorySlug, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedReviewsByProduct = `-- name: CountPublishedReviewsByProduct :one
SELECT count(*) FROM reviews
WHERE product_id = $1 AND status = 'published'
`

// CountPublishedReviewsByProduct is the total for the review-list envelope — the SAME product_id +
// status='published' filter as ListReviewsByProduct, no sort/limit. It runs alongside the list as a
// second autocommit read; a concurrent review write between the two can skew the total by one. That is
// cosmetic (a display count that self-heals next request) and never a money value, so we accept it
// rather than pay for a snapshot transaction (documented on the repo method).
func (q *Queries) CountPublishedReviewsByProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedReviewsByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories WHERE id = $1 RETURNING id
`

// DeleteCategory is a HARD delete, allowed only for a category no product references: products.category_id is
// NOT NULL REFERENCES categories(id) with the default NO ACTION (migration 000003), so deleting a category
// still in use raises a foreign_key_violation the handler maps to 409 CATEGORY_IN_USE (reassign or archive the
// products first). RETURNING id so a missing row surfaces as ErrNoRows→404, mirroring DeleteProduct.
func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	err := row.Scan(&id)
	return id, err
}

const deleteColor = `-- name: DeleteColor :one
DELETE FROM colors WHERE id = $1 AND product_id = $2 RETURNING id
`

type DeleteColorParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
}

func (q *Queries) DeleteColor(ctx context.Context, arg DeleteColorParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteColor, arg.ID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOption = `-- name: DeleteOption :one
DELETE FROM options WHERE id = $1 AND product_id = $2 RETURNING id
`

type DeleteOptionParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
}

func (q *Queries) DeleteOption(ctx context.Context, arg DeleteOptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteOption, arg.ID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOptionChoice = `-- name: DeleteOptionChoice :one
DELETE FROM option_choices WHERE id = $1 AND option_id = $2 RETURNING id
`

type DeleteOptionChoiceParams struct {
	ID       uuid.UUID `json:"id"`
	OptionID uuid.UUID `json:"optionId"`
}

func (q *Queries) DeleteOptionChoice(ctx context.Context, arg DeleteOptionChoiceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteOptionChoice, arg.ID, arg.OptionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePart = `-- name: DeletePart :one
DELETE FROM parts WHERE id = $1 AND product_id = $2 RETURNING id
`

type DeletePartParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
}

func (q *Queries) DeletePart(ctx context.Context, arg DeletePartParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deletePart, arg.ID, arg.ProductID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 RETURNING id
`

// DeleteProduct is a HARD delete, allowed only for never-ordered/never-rendered products (drafts, mistakes):
// order_items and asset_jobs reference products ON DELETE RESTRICT (migrations 000005/000006), so deleting a
// product with history raises a foreign_key_violation the handler maps to 409 "hãy lưu trữ thay vì xoá" — the
// reversible "remove from store" path is PATCH status→archived. colors/options are ON DELETE CASCADE, so a
// successful delete cleans them up. RETURNING id so a missing row surfaces as ErrNoRows→404.
func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	err := row.Scan(&id)
	return id, err
}

const getOptionByProduct = `-- name: GetOptionByProduct :one
SELECT id, product_id, label, description, type, price_delta, max_chars FROM options WHERE id = $1 AND product_id = $2
`

type GetOptionByProductParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
}

// GetOptionByProduct scopes an option to its product — the choice handlers call it to validate the
// {optionId} in the path belongs to {id} before touching its choices (a choice under another product's
// option → 404), the option-level analogue of the (id, product_id) scoping on colours/options.
func (q *Queries) GetOptionByProduct(ctx context.Context, arg GetOptionByProductParams) (Option, error) {
	row := q.db.QueryRow(ctx, getOptionByProduct, arg.ID, arg.ProductID)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.PriceDelta,
		&i.MaxChars,
	)
	return i, err
}

const getPartByProduct = `-- name: GetPartByProduct :one
SELECT id, product_id, name, display_order, est_filament_qty FROM parts WHERE id = $1 AND product_id = $2
`

type GetPartByProductParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
}

// GetPartByProduct scopes a part to its product — the colour handlers call it to validate that a colour's
// claimed partId belongs to the SAME product before assigning it (ADR-037: colour ∈ part ∈ product), so a
// colour can never be grouped under another product's part. Missing → ErrNoRows → 400 field(partId).
func (q *Queries) GetPartByProduct(ctx context.Context, arg GetPartByProductParams) (Part, error) {
	row := q.db.QueryRow(ctx, getPartByProduct, arg.ID, arg.ProductID)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.DisplayOrder,
		&i.EstFilamentQty,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at, model3d_view, est_filament_qty, est_print_minutes, product_type FROM products WHERE id = $1
`

// GetProductByID is the by-id read the checkout handler (PR-3g) needs to derive a
// server-authoritative UnitPrice from base_price (never a client price). ProductBySlug is the
// storefront read; this is the intake read. Colors/options are validated via the existing
// ListColorsByProduct / ListOptionsByProduct (membership + availability checked in-process).
func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BasePrice,
		&i.Dimensions,
		&i.Material,
		&i.Model3dUrl,
		&i.Images,
		&i.Status,
		&i.RatingAvg,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.Model3dView,
		&i.EstFilamentQty,
		&i.EstPrintMinutes,
		&i.ProductType,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at, model3d_view, est_filament_qty, est_print_minutes, product_type FROM products WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BasePrice,
		&i.Dimensions,
		&i.Material,
		&i.Model3dUrl,
		&i.Images,
		&i.Status,
		&i.RatingAvg,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.Model3dView,
		&i.EstFilamentQty,
		&i.EstPrintMinutes,
		&i.ProductType,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one

INSERT INTO categories (id, slug, name, display_order)
VALUES ($1, $2, $3, (SELECT coalesce(max(display_order) + 1, 0) FROM categories))
RETURNING id, slug, name, display_order, description, image_url, visible
`

type InsertCategoryParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

// catalog.sql — catalog read/write queries (PR-2c). spec.md §02. Inserts return the row so
// callers (slice-3 admin handlers, tests) get the persisted record back.
// InsertCategory creates a category and APPENDS it to the end of the menu order (display_order = current
// max + 1, or 0 for the first). description/image_url/visible take their column defaults (”, ”, true) — a
// new category is shown and un-described until the owner edits it. slug/name are the only create inputs
// (design "+ Thêm danh mục"); the rich fields are set from the edit panel (UpdateCategory). The subquery
// reads the pre-insert max (the new row is not visible to its own INSERT), so appends never collide.
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.ID, arg.Slug, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayOrder,
		&i.Description,
		&i.ImageUrl,
		&i.Visible,
	)
	return i, err
}

const insertColor = `-- name: InsertColor :one
INSERT INTO colors (id, product_id, name, hex, available, price_delta, part_id, filament_material_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, name, hex, available, price_delta, part_id, filament_material_id
`

type InsertColorParams struct {
	ID                 uuid.UUID   `json:"id"`
	ProductID          uuid.UUID   `json:"productId"`
	Name               string      `json:"name"`
	Hex                string      `json:"hex"`
	Available          bool        `json:"available"`
	PriceDelta         int64       `json:"priceDelta"`
	PartID             pgtype.UUID `json:"partId"`
	FilamentMaterialID pgtype.UUID `json:"filamentMaterialId"`
}

// InsertColor takes an optional part_id (ADR-037): NULL = flat product-level colour (legacy/default);
// set = the colour belongs to that part. The handler validates the part ∈ the same product first
// (GetPartByProduct) so a colour can never be grouped under another product's part.
func (q *Queries) InsertColor(ctx context.Context, arg InsertColorParams) (Color, error) {
	row := q.db.QueryRow(ctx, insertColor,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Hex,
		arg.Available,
		arg.PriceDelta,
		arg.PartID,
		arg.FilamentMaterialID,
	)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Hex,
		&i.Available,
		&i.PriceDelta,
		&i.PartID,
		&i.FilamentMaterialID,
	)
	return i, err
}

const insertOption = `-- name: InsertOption :one
INSERT INTO options (id, product_id, label, description, type, price_delta, max_chars)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, label, description, type, price_delta, max_chars
`

type InsertOptionParams struct {
	ID          uuid.UUID  `json:"id"`
	ProductID   uuid.UUID  `json:"productId"`
	Label       string     `json:"label"`
	Description string     `json:"description"`
	Type        OptionType `json:"type"`
	PriceDelta  int64      `json:"priceDelta"`
	MaxChars    *int32     `json:"maxChars"`
}

func (q *Queries) InsertOption(ctx context.Context, arg InsertOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, insertOption,
		arg.ID,
		arg.ProductID,
		arg.Label,
		arg.Description,
		arg.Type,
		arg.PriceDelta,
		arg.MaxChars,
	)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.PriceDelta,
		&i.MaxChars,
	)
	return i, err
}

const insertOptionChoice = `-- name: InsertOptionChoice :one

INSERT INTO option_choices (id, option_id, label, description, price_delta, display_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, option_id, label, description, price_delta, display_order
`

type InsertOptionChoiceParams struct {
	ID           uuid.UUID `json:"id"`
	OptionID     uuid.UUID `json:"optionId"`
	Label        string    `json:"label"`
	Description  string    `json:"description"`
	PriceDelta   int64     `json:"priceDelta"`
	DisplayOrder int32     `json:"displayOrder"`
}

// === ADR-037 configurator: option choices (enumerated values for a `choice` option) ===
func (q *Queries) InsertOptionChoice(ctx context.Context, arg InsertOptionChoiceParams) (OptionChoice, error) {
	row := q.db.QueryRow(ctx, insertOptionChoice,
		arg.ID,
		arg.OptionID,
		arg.Label,
		arg.Description,
		arg.PriceDelta,
		arg.DisplayOrder,
	)
	var i OptionChoice
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.Label,
		&i.Description,
		&i.PriceDelta,
		&i.DisplayOrder,
	)
	return i, err
}

const insertPart = `-- name: InsertPart :one

INSERT INTO parts (id, product_id, name, display_order, est_filament_qty)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, name, display_order, est_filament_qty
`

type InsertPartParams struct {
	ID             uuid.UUID `json:"id"`
	ProductID      uuid.UUID `json:"productId"`
	Name           string    `json:"name"`
	DisplayOrder   int32     `json:"displayOrder"`
	EstFilamentQty int64     `json:"estFilamentQty"`
}

// === ADR-037 configurator: parts (named part groups, each with its own colour set) ===
func (q *Queries) InsertPart(ctx context.Context, arg InsertPartParams) (Part, error) {
	row := q.db.QueryRow(ctx, insertPart,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.DisplayOrder,
		arg.EstFilamentQty,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.DisplayOrder,
		&i.EstFilamentQty,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
  id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, est_filament_qty, est_print_minutes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at, model3d_view, est_filament_qty, est_print_minutes, product_type
`

type InsertProductParams struct {
	ID              uuid.UUID     `json:"id"`
	Slug            string        `json:"slug"`
	Name            string        `json:"name"`
	Description     string        `json:"description"`
	CategoryID      uuid.UUID     `json:"categoryId"`
	BasePrice       int64         `json:"basePrice"`
	Dimensions      []byte        `json:"dimensions"`
	Material        string        `json:"material"`
	Model3dUrl      string        `json:"model3dUrl"`
	Images          []byte        `json:"images"`
	Status          ProductStatus `json:"status"`
	EstFilamentQty  int64         `json:"estFilamentQty"`
	EstPrintMinutes int32         `json:"estPrintMinutes"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.BasePrice,
		arg.Dimensions,
		arg.Material,
		arg.Model3dUrl,
		arg.Images,
		arg.Status,
		arg.EstFilamentQty,
		arg.EstPrintMinutes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BasePrice,
		&i.Dimensions,
		&i.Material,
		&i.Model3dUrl,
		&i.Images,
		&i.Status,
		&i.RatingAvg,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.Model3dView,
		&i.EstFilamentQty,
		&i.EstPrintMinutes,
		&i.ProductType,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (id, product_id, customer_id, rating, body, images, reply, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, customer_id, rating, body, images, reply, status, created_at
`

type InsertReviewParams struct {
	ID         uuid.UUID    `json:"id"`
	ProductID  uuid.UUID    `json:"productId"`
	CustomerID pgtype.UUID  `json:"customerId"`
	Rating     int16        `json:"rating"`
	Body       string       `json:"body"`
	Images     []byte       `json:"images"`
	Reply      []byte       `json:"reply"`
	Status     ReviewStatus `json:"status"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.ID,
		arg.ProductID,
		arg.CustomerID,
		arg.Rating,
		arg.Body,
		arg.Images,
		arg.Reply,
		arg.Status,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CustomerID,
		&i.Rating,
		&i.Body,
		&i.Images,
		&i.Reply,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, slug, name, base_price, category_id, images, rating_avg, review_count
FROM products
WHERE status = 'active'
  AND (
    $1::text IS NULL
    OR category_id = (SELECT id FROM categories WHERE slug = $1::text)
  )
  AND (
    $2::text IS NULL
    OR to_tsvector('simple', immutable_unaccent(name || ' ' || description))
       @@ plainto_tsquery('simple', immutable_unaccent($2::text))
  )
ORDER BY
  CASE WHEN $3::text = 'price_asc'  THEN base_price END ASC,
  CASE WHEN $3::text = 'price_desc' THEN base_price END DESC,
  CASE WHEN $3::text = 'rating'     THEN rating_avg END DESC NULLS LAST,
  created_at DESC,
  id DESC
LIMIT $5::int OFFSET $4::int
`

type ListActiveProductsParams struct {
	CategorySlug *string `json:"categorySlug"`
	Search       *string `json:"search"`
	Sort         string  `json:"sort"`
	PageOffset   int32   `json:"pageOffset"`
	PageLimit    int32   `json:"pageLimit"`
}

type ListActiveProductsRow struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	BasePrice   int64     `json:"basePrice"`
	CategoryID  uuid.UUID `json:"categoryId"`
	Images      []byte    `json:"images"`
	RatingAvg   *float32  `json:"ratingAvg"`
	ReviewCount int32     `json:"reviewCount"`
}

// ListActiveProducts is the storefront catalog list (PR-P1-c). It returns ACTIVE products ONLY as a
// CARD projection (a subset of columns — no description/model3d_url, and no colors/options join → no
// N+1). The optional category filter matches by category SLUG via an UNCORRELATED subquery (Postgres
// runs it once as an InitPlan, not per row); an unknown slug simply matches no rows → an empty page,
// never a 404. Sort is a WHITELISTED CASE so the ORDER BY can never be built from raw client text; the
// non-selected CASE arms evaluate to a constant NULL and drop out, and created_at DESC, id DESC give a
// deterministic TOTAL order so OFFSET pagination is stable across pages. @page_limit is bounded by the
// handler (pageSize <= 48).
//
// The optional @search predicate (PR-P1-e, ADR-016) is the no-accent full-text filter: it is ANDed INSIDE
// the active-only + category scope, so search can NEVER surface a draft/archived row (the same non-leak
// discipline as the base list). The client term is never interpolated — it is parameterized through
// plainto_tsquery, and both sides are accent-folded via immutable_unaccent so "den" matches "đèn". The
// to_tsvector expression is byte-identical to the products_search_idx functional GIN index (000012) so the
// planner uses it. NULL search (the common case) short-circuits to the exact pre-P1-e query — no regression.
// Sort is unchanged under search (still the whitelist, default newest): ADR-016 scopes this to exact-token
// matching on a tiny catalog, so relevance ranking (ts_rank) is a deliberate non-goal (it would also mean a
// new sort enum value — a contract change P1-e avoids).
func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]ListActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProducts,
		arg.CategorySlug,
		arg.Search,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductsRow
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BasePrice,
			&i.CategoryID,
			&i.Images,
			&i.RatingAvg,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminProducts = `-- name: ListAdminProducts :many
SELECT id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at, model3d_view, est_filament_qty, est_print_minutes, product_type FROM products
WHERE ($1::product_status IS NULL OR status = $1::product_status)
ORDER BY created_at DESC, id DESC
`

// ListAdminProducts is the admin catalog list (P3-j / P3-k) — the INTERNAL projection that shows EVERY
// status (active/draft/archived), unlike the storefront's active-only ListActiveProducts (ADR-032: admin
// may see unreleased rows). The optional status narg drives the "Tất cả/Đang bán/Nháp/Lưu trữ" tabs: NULL =
// all statuses, else exact-match. No pagination/count — a made-to-order catalog is small and admin-curated
// (same "fits one response" scale as ListCategories), so the FE lists+searches the whole set client-side;
// add a page window here if the catalog ever grows large. Newest first with an id tiebreak = deterministic
// total order.
func (q *Queries) ListAdminProducts(ctx context.Context, status NullProductStatus) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAdminProducts, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.BasePrice,
			&i.Dimensions,
			&i.Material,
			&i.Model3dUrl,
			&i.Images,
			&i.Status,
			&i.RatingAvg,
			&i.ReviewCount,
			&i.CreatedAt,
			&i.Model3dView,
			&i.EstFilamentQty,
			&i.EstPrintMinutes,
			&i.ProductType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT c.id, c.slug, c.name, c.display_order, c.description, c.image_url, c.visible, count(p.id) AS product_count
FROM categories c
LEFT JOIN products p ON p.category_id = c.id
GROUP BY c.id
ORDER BY c.display_order, c.name, c.slug
`

type ListAllCategoriesRow struct {
	ID           uuid.UUID `json:"id"`
	Slug         string    `json:"slug"`
	Name         string    `json:"name"`
	DisplayOrder int32     `json:"displayOrder"`
	Description  string    `json:"description"`
	ImageUrl     string    `json:"imageUrl"`
	Visible      bool      `json:"visible"`
	ProductCount int64     `json:"productCount"`
}

// ListAllCategories is the ADMIN category list (P3-o) — the INTERNAL projection that returns EVERY category,
// including empty ones and those whose only products are draft/archived, unlike the storefront-facing
// ListCategories (which hides categories with no ACTIVE product). Each row carries product_count = the number
// of products referencing it across ALL statuses (LEFT JOIN so an empty category still appears, with count 0).
// That count is the load-bearing admin figure: it tells the owner which categories are safe to delete (a
// non-zero count means DeleteCategory will trip the products.category_id FK → 409). No pagination — categories
// are a small, admin-curated set (same "fits one response" scale as ListCategories/ListAdminProducts). Ordered
// by the owner-set display_order first (so the admin list mirrors the storefront menu order the owner is
// arranging), then name/slug as the deterministic tiebreak. Unlike ListCategories it does NOT filter on
// `visible` — the admin sees hidden categories too (with their toggle off), that is the point of the screen.
func (q *Queries) ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCategoriesRow
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DisplayOrder,
			&i.Description,
			&i.ImageUrl,
			&i.Visible,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReviews = `-- name: ListAllReviews :many
SELECT r.id, r.product_id, p.name AS product_name, r.customer_id, c.name AS customer_name,
       r.rating, r.body, r.images, r.reply, r.status, r.created_at
FROM reviews r
JOIN products p ON p.id = r.product_id
LEFT JOIN customers c ON c.id = r.customer_id
WHERE ($1::review_status IS NULL OR r.status = $1::review_status)
ORDER BY r.created_at DESC, r.id DESC
`

type ListAllReviewsRow struct {
	ID           uuid.UUID          `json:"id"`
	ProductID    uuid.UUID          `json:"productId"`
	ProductName  string             `json:"productName"`
	CustomerID   pgtype.UUID        `json:"customerId"`
	CustomerName *string            `json:"customerName"`
	Rating       int16              `json:"rating"`
	Body         string             `json:"body"`
	Images       []byte             `json:"images"`
	Reply        []byte             `json:"reply"`
	Status       ReviewStatus       `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

// ListAllReviews is the ADMIN review-moderation list (P3-m) — EVERY review across ALL products, both
// 'published' AND 'hidden' (the moderation surface, unlike the storefront ListReviewsByProduct which is
// published-only at the SQL source). It is the INTERNAL projection: it JOINs the product name (for "review
// on <product>") and LEFT JOINs the reviewer's name (customer_id is nullable — guests may review — so
// customer_name is null for a guest). Reviewer identity is admin-only PII (PDPL): it appears here behind the
// admin auth wall, never on the public Review. Optional status filter (nullable narg = Tất cả / a tab),
// mirroring ListAdminProducts. No pagination — a made-to-order shop's review set is small and the FE derives
// its tabs (Chờ trả lời / Đã trả lời / Có ảnh) client-side. -- ponytail: add a page window here if reviews
// ever grow large. Newest first with an id tiebreak = a deterministic total order.
func (q *Queries) ListAllReviews(ctx context.Context, status NullReviewStatus) ([]ListAllReviewsRow, error) {
	rows, err := q.db.Query(ctx, listAllReviews, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReviewsRow
	for rows.Next() {
		var i ListAllReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.CustomerID,
			&i.CustomerName,
			&i.Rating,
			&i.Body,
			&i.Images,
			&i.Reply,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, display_order, description, image_url, visible FROM categories
WHERE visible AND EXISTS (SELECT 1 FROM products WHERE products.category_id = categories.id AND products.status = 'active')
ORDER BY display_order, name, slug
`

// ListCategories is the storefront category list (PR-P1-d): the BROWSABLE taxonomy the catalog-browse chips
// render (spec §02). It returns only categories that contain at least one ACTIVE product — the EXISTS
// subquery applies the SAME non-leak-at-the-SQL-source discipline as ListActiveProducts (CAT-02). A category
// whose only products are draft/archived (products default to status='draft', and category_id is NOT NULL),
// or which is empty, is a hidden grouping: surfacing it would both dead-end the chip (→ an empty
// /products?category= page) AND leak an unreleased category name — the exact catalog-existence info the
// product reads deliberately withhold. Categories are a small, admin-curated, near-static set (created only
// via admin CreateCategory — no user-generated path), so there is no filter/pagination: the browsable set
// fits one response. The order is a deterministic TOTAL order (name first for a human-friendly A→Z, slug —
// UNIQUE — as the tiebreak) so two categories sharing a display name never flap position; a stable order
// keeps the response ETag stable. No browsable category → zero rows → the handler renders `[]`, not 404.
// Two gates now decide menu membership (P3-o slice o-2): the owner's explicit `visible` toggle AND the
// active-product EXISTS — a category shows iff BOTH hold (an owner hide removes a category with active
// products from the menu; the auto-hide still catches empty/draft-only ones). Ordered by the owner-set
// display_order first (the drag-to-reorder result), then name/slug as the deterministic tiebreak.
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DisplayOrder,
			&i.Description,
			&i.ImageUrl,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoicesByProduct = `-- name: ListChoicesByProduct :many
SELECT oc.id, oc.option_id, oc.label, oc.description, oc.price_delta, oc.display_order FROM option_choices oc
JOIN options o ON o.id = oc.option_id
WHERE o.product_id = $1
ORDER BY oc.option_id, oc.display_order, oc.id
`

// ListChoicesByProduct returns every option_choice for a product's options (joined via options.product_id),
// for the editor's Product-detail assembly (the handler groups them by option_id into Option.choices[]).
// Ordered by option then display_order for a deterministic nesting.
func (q *Queries) ListChoicesByProduct(ctx context.Context, productID uuid.UUID) ([]OptionChoice, error) {
	rows, err := q.db.Query(ctx, listChoicesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OptionChoice
	for rows.Next() {
		var i OptionChoice
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.Label,
			&i.Description,
			&i.PriceDelta,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColorsByProduct = `-- name: ListColorsByProduct :many
SELECT id, product_id, name, hex, available, price_delta, part_id, filament_material_id FROM colors WHERE product_id = $1 ORDER BY name
`

func (q *Queries) ListColorsByProduct(ctx context.Context, productID uuid.UUID) ([]Color, error) {
	rows, err := q.db.Query(ctx, listColorsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Color
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Hex,
			&i.Available,
			&i.PriceDelta,
			&i.PartID,
			&i.FilamentMaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByProduct = `-- name: ListOptionsByProduct :many
SELECT id, product_id, label, description, type, price_delta, max_chars FROM options WHERE product_id = $1 ORDER BY label
`

func (q *Queries) ListOptionsByProduct(ctx context.Context, productID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Label,
			&i.Description,
			&i.Type,
			&i.PriceDelta,
			&i.MaxChars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsByProduct = `-- name: ListPartsByProduct :many
SELECT id, product_id, name, display_order, est_filament_qty FROM parts WHERE product_id = $1 ORDER BY display_order, id
`

func (q *Queries) ListPartsByProduct(ctx context.Context, productID uuid.UUID) ([]Part, error) {
	rows, err := q.db.Query(ctx, listPartsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.DisplayOrder,
			&i.EstFilamentQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByStatus = `-- name: ListProductsByStatus :many
SELECT id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at, model3d_view, est_filament_qty, est_print_minutes, product_type FROM products WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProductsByStatus(ctx context.Context, status ProductStatus) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.BasePrice,
			&i.Dimensions,
			&i.Material,
			&i.Model3dUrl,
			&i.Images,
			&i.Status,
			&i.RatingAvg,
			&i.ReviewCount,
			&i.CreatedAt,
			&i.Model3dView,
			&i.EstFilamentQty,
			&i.EstPrintMinutes,
			&i.ProductType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProduct = `-- name: ListReviewsByProduct :many
SELECT id, rating, body, images, reply, created_at
FROM reviews
WHERE product_id = $1 AND status = 'published'
ORDER BY created_at DESC, id DESC
LIMIT $3::int OFFSET $2::int
`

type ListReviewsByProductParams struct {
	ProductID  uuid.UUID `json:"productId"`
	PageOffset int32     `json:"pageOffset"`
	PageLimit  int32     `json:"pageLimit"`
}

type ListReviewsByProductRow struct {
	ID        uuid.UUID          `json:"id"`
	Rating    int16              `json:"rating"`
	Body      string             `json:"body"`
	Images    []byte             `json:"images"`
	Reply     []byte             `json:"reply"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

// ListReviewsByProduct is the storefront product-review list (PR-P1-l). It returns PUBLISHED reviews
// ONLY — the status='published' predicate lives HERE at the SQL source, the same non-leak discipline as
// ListActiveProducts' status='active': a hidden (moderated-away) review can never surface on the public
// list, no matter what the handler does. It is a CONTENT projection — id/rating/body/images/reply/
// created_at, but NOT customer_id — so no reviewer PII (a nullable FK; guests may review) ever leaves the
// DB for this public endpoint. Newest first with an id tiebreak gives a deterministic TOTAL order so
// OFFSET pagination is stable across pages and the response ETag stays stable; @page_limit is bounded by
// the handler (pageSize <= 48). No sort arm in Phase 1 (newest only — an additive sort is a later PR).
func (q *Queries) ListReviewsByProduct(ctx context.Context, arg ListReviewsByProductParams) ([]ListReviewsByProductRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByProduct, arg.ProductID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByProductRow
	for rows.Next() {
		var i ListReviewsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Body,
			&i.Images,
			&i.Reply,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderCategories = `-- name: ReorderCategories :exec
UPDATE categories AS c
SET display_order = v.ord - 1
FROM (SELECT id, ord FROM unnest($1::uuid[]) WITH ORDINALITY AS t(id, ord)) AS v
WHERE c.id = v.id
`

// ReorderCategories sets each category's display_order to its position in the given id list (0-based), in
// one atomic statement over the whole ordered set the admin drag produced. unnest(... ) WITH ORDINALITY
// pairs each id with its 1-based index (ord), minus 1 for a 0-based order. Ids absent from the list keep
// their current order (the FE sends the FULL list after a drag, so that is a no-op in practice); an unknown
// id matches no row (harmless). Owner-only at the handler.
func (q *Queries) ReorderCategories(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, reorderCategories, ids)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET slug = $2, name = $3, description = $4, image_url = $5, visible = $6
WHERE id = $1
RETURNING id, slug, name, display_order, description, image_url, visible
`

type UpdateCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"imageUrl"`
	Visible     bool      `json:"visible"`
}

// UpdateCategory saves a category's editable fields (P3-o): slug, name, and the o-2 menu metadata
// (description, image_url, visible). display_order is NOT set here — it moves only via ReorderCategories
// (the drag), so a Save from the edit panel never disturbs the menu order. slug stays mutable — a changed
// slug that collides with another category trips the UNIQUE(slug) constraint, which the handler maps to a
// 400 field error (never a 500), mirroring UpdateProduct. RETURNING so an unknown id (0 rows → ErrNoRows)
// surfaces as 404.
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Visible,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DisplayOrder,
		&i.Description,
		&i.ImageUrl,
		&i.Visible,
	)
	return i, err
}

const updateColor = `-- name: UpdateColor :one
UPDATE colors
SET name = $3, hex = $4, available = $5, price_delta = $6, part_id = $7, filament_material_id = $8
WHERE id = $1 AND product_id = $2
RETURNING id, product_id, name, hex, available, price_delta, part_id, filament_material_id
`

type UpdateColorParams struct {
	ID                 uuid.UUID   `json:"id"`
	ProductID          uuid.UUID   `json:"productId"`
	Name               string      `json:"name"`
	Hex                string      `json:"hex"`
	Available          bool        `json:"available"`
	PriceDelta         int64       `json:"priceDelta"`
	PartID             pgtype.UUID `json:"partId"`
	FilamentMaterialID pgtype.UUID `json:"filamentMaterialId"`
}

// UpdateColor / DeleteColor are scoped by BOTH id AND product_id (P3-j) so a colorId belonging to another
// product (a mismatched /products/{id}/colors/{colorId} path) matches no row → ErrNoRows→404, never a
// cross-product edit. RETURNING lets the handler 404 on a stale id.
func (q *Queries) UpdateColor(ctx context.Context, arg UpdateColorParams) (Color, error) {
	row := q.db.QueryRow(ctx, updateColor,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Hex,
		arg.Available,
		arg.PriceDelta,
		arg.PartID,
		arg.FilamentMaterialID,
	)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Hex,
		&i.Available,
		&i.PriceDelta,
		&i.PartID,
		&i.FilamentMaterialID,
	)
	return i, err
}

const updateOption = `-- name: UpdateOption :one
UPDATE options
SET label = $3, description = $4, type = $5, price_delta = $6, max_chars = $7
WHERE id = $1 AND product_id = $2
RETURNING id, product_id, label, description, type, price_delta, max_chars
`

type UpdateOptionParams struct {
	ID          uuid.UUID  `json:"id"`
	ProductID   uuid.UUID  `json:"productId"`
	Label       string     `json:"label"`
	Description string     `json:"description"`
	Type        OptionType `json:"type"`
	PriceDelta  int64      `json:"priceDelta"`
	MaxChars    *int32     `json:"maxChars"`
}

// UpdateOption / DeleteOption are scoped by BOTH id AND product_id (P3-j), same cross-product guard as the
// color mutations: an optionId under the wrong product → no row → 404.
func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, updateOption,
		arg.ID,
		arg.ProductID,
		arg.Label,
		arg.Description,
		arg.Type,
		arg.PriceDelta,
		arg.MaxChars,
	)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.PriceDelta,
		&i.MaxChars,
	)
	return i, err
}

const updateOptionChoice = `-- name: UpdateOptionChoice :one
UPDATE option_choices SET label = $3, description = $4, price_delta = $5, display_order = $6
WHERE id = $1 AND option_id = $2
RETURNING id, option_id, label, description, price_delta, display_order
`

type UpdateOptionChoiceParams struct {
	ID           uuid.UUID `json:"id"`
	OptionID     uuid.UUID `json:"optionId"`
	Label        string    `json:"label"`
	Description  string    `json:"description"`
	PriceDelta   int64     `json:"priceDelta"`
	DisplayOrder int32     `json:"displayOrder"`
}

// UpdateOptionChoice / DeleteOptionChoice are scoped by BOTH id AND option_id (a choiceId under another
// option → no row → 404); the handler has already confirmed the option ∈ product via GetOptionByProduct.
func (q *Queries) UpdateOptionChoice(ctx context.Context, arg UpdateOptionChoiceParams) (OptionChoice, error) {
	row := q.db.QueryRow(ctx, updateOptionChoice,
		arg.ID,
		arg.OptionID,
		arg.Label,
		arg.Description,
		arg.PriceDelta,
		arg.DisplayOrder,
	)
	var i OptionChoice
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.Label,
		&i.Description,
		&i.PriceDelta,
		&i.DisplayOrder,
	)
	return i, err
}

const updatePart = `-- name: UpdatePart :one
UPDATE parts SET name = $3, display_order = $4, est_filament_qty = $5
WHERE id = $1 AND product_id = $2
RETURNING id, product_id, name, display_order, est_filament_qty
`

type UpdatePartParams struct {
	ID             uuid.UUID `json:"id"`
	ProductID      uuid.UUID `json:"productId"`
	Name           string    `json:"name"`
	DisplayOrder   int32     `json:"displayOrder"`
	EstFilamentQty int64     `json:"estFilamentQty"`
}

// UpdatePart / DeletePart are scoped by BOTH id AND product_id (a partId under another product → no row →
// 404), the same cross-product guard as UpdateColor/UpdateOption. Deleting a part CASCADEs its colours
// (000015); a colour pinned by an order_item (FK NO ACTION) blocks the delete → 23503 → 409 (archive).
func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, updatePart,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.DisplayOrder,
		arg.EstFilamentQty,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.DisplayOrder,
		&i.EstFilamentQty,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET slug = $2, name = $3, description = $4, category_id = $5, base_price = $6,
    dimensions = $7, material = $8, images = $9, status = $10, est_filament_qty = $11, est_print_minutes = $12
WHERE id = $1
RETURNING id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at, model3d_view, est_filament_qty, est_print_minutes, product_type
`

type UpdateProductParams struct {
	ID              uuid.UUID     `json:"id"`
	Slug            string        `json:"slug"`
	Name            string        `json:"name"`
	Description     string        `json:"description"`
	CategoryID      uuid.UUID     `json:"categoryId"`
	BasePrice       int64         `json:"basePrice"`
	Dimensions      []byte        `json:"dimensions"`
	Material        string        `json:"material"`
	Images          []byte        `json:"images"`
	Status          ProductStatus `json:"status"`
	EstFilamentQty  int64         `json:"estFilamentQty"`
	EstPrintMinutes int32         `json:"estPrintMinutes"`
}

// UpdateProduct saves the editable fields of a product (P3-j). It deliberately does NOT touch model3d_url:
// that column is owned by the asset pipeline (P3-j-b sets it when a model finishes ingesting), so the
// product editor form can never blank it. slug stays mutable — a changed slug that collides trips the
// UNIQUE(slug) constraint, which the handler maps to a 400 field error (never a 500).
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.BasePrice,
		arg.Dimensions,
		arg.Material,
		arg.Images,
		arg.Status,
		arg.EstFilamentQty,
		arg.EstPrintMinutes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BasePrice,
		&i.Dimensions,
		&i.Material,
		&i.Model3dUrl,
		&i.Images,
		&i.Status,
		&i.RatingAvg,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.Model3dView,
		&i.EstFilamentQty,
		&i.EstPrintMinutes,
		&i.ProductType,
	)
	return i, err
}

const updateProductModelView = `-- name: UpdateProductModelView :execrows
UPDATE products SET model3d_view = $2 WHERE id = $1
`

type UpdateProductModelViewParams struct {
	ID          uuid.UUID `json:"id"`
	Model3dView []byte    `json:"model3dView"`
}

// UpdateProductModelView persists the owner's saved default 3D-viewer camera pose (ADR-038) as the whole
// atomic model3d_view jsonb blob ({orbitTheta,orbitPhi,orbitRadius,targetX,targetY,targetZ}). It is a
// separate write from UpdateProduct (the design's "Lưu góc mặc định" is its own button) and touches no
// other column — never pricing. :execrows so an unknown id (0 rows) surfaces as ErrNoRows→404; the handler
// returns 204 (the editor keeps the pose it just sent — nothing new to echo).
func (q *Queries) UpdateProductModelView(ctx context.Context, arg UpdateProductModelViewParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProductModelView, arg.ID, arg.Model3dView)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReviewModeration = `-- name: UpdateReviewModeration :one
UPDATE reviews
SET status = coalesce($1::review_status, status),
    reply  = CASE WHEN $2::boolean THEN $3 ELSE reply END
WHERE id = $4
RETURNING id
`

type UpdateReviewModerationParams struct {
	Status   NullReviewStatus `json:"status"`
	SetReply bool             `json:"setReply"`
	Reply    []byte           `json:"reply"`
	ID       uuid.UUID        `json:"id"`
}

// UpdateReviewModeration is the admin moderation write (P3-m): change a review's status (publish ↔ hide)
// and/or set its shop reply, in one partial UPDATE. status is a nullable narg (omit ⇒ unchanged, via
// coalesce). reply is touched only when @set_reply is true (so a plain hide/unhide leaves an existing reply
// intact); the handler builds the {body, at} jsonb (or passes it through). No outbox — review moderation is
// an internal content decision, not a domain event (plan §5). RETURNING id so an unknown id (0 rows →
// ErrNoRows) surfaces as 404; the handler answers 204 (the FE re-reads the list).
func (q *Queries) UpdateReviewModeration(ctx context.Context, arg UpdateReviewModerationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateReviewModeration,
		arg.Status,
		arg.SetReply,
		arg.Reply,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
