// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at FROM products WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BasePrice,
		&i.Dimensions,
		&i.Material,
		&i.Model3dUrl,
		&i.Images,
		&i.Status,
		&i.RatingAvg,
		&i.ReviewCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one

INSERT INTO categories (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name
`

type InsertCategoryParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

// catalog.sql — catalog read/write queries (PR-2c). spec.md §02. Inserts return the row so
// callers (slice-3 admin handlers, tests) get the persisted record back.
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.ID, arg.Slug, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const insertColor = `-- name: InsertColor :one
INSERT INTO colors (id, product_id, name, hex, available, price_delta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, name, hex, available, price_delta
`

type InsertColorParams struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"productId"`
	Name       string    `json:"name"`
	Hex        string    `json:"hex"`
	Available  bool      `json:"available"`
	PriceDelta int64     `json:"priceDelta"`
}

func (q *Queries) InsertColor(ctx context.Context, arg InsertColorParams) (Color, error) {
	row := q.db.QueryRow(ctx, insertColor,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Hex,
		arg.Available,
		arg.PriceDelta,
	)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Hex,
		&i.Available,
		&i.PriceDelta,
	)
	return i, err
}

const insertOption = `-- name: InsertOption :one
INSERT INTO options (id, product_id, label, description, type, price_delta, max_chars)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, label, description, type, price_delta, max_chars
`

type InsertOptionParams struct {
	ID          uuid.UUID  `json:"id"`
	ProductID   uuid.UUID  `json:"productId"`
	Label       string     `json:"label"`
	Description string     `json:"description"`
	Type        OptionType `json:"type"`
	PriceDelta  int64      `json:"priceDelta"`
	MaxChars    *int32     `json:"maxChars"`
}

func (q *Queries) InsertOption(ctx context.Context, arg InsertOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, insertOption,
		arg.ID,
		arg.ProductID,
		arg.Label,
		arg.Description,
		arg.Type,
		arg.PriceDelta,
		arg.MaxChars,
	)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.PriceDelta,
		&i.MaxChars,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
  id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at
`

type InsertProductParams struct {
	ID          uuid.UUID     `json:"id"`
	Slug        string        `json:"slug"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	CategoryID  uuid.UUID     `json:"categoryId"`
	BasePrice   int64         `json:"basePrice"`
	Dimensions  []byte        `json:"dimensions"`
	Material    string        `json:"material"`
	Model3dUrl  string        `json:"model3dUrl"`
	Images      []byte        `json:"images"`
	Status      ProductStatus `json:"status"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.BasePrice,
		arg.Dimensions,
		arg.Material,
		arg.Model3dUrl,
		arg.Images,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BasePrice,
		&i.Dimensions,
		&i.Material,
		&i.Model3dUrl,
		&i.Images,
		&i.Status,
		&i.RatingAvg,
		&i.ReviewCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (id, product_id, customer_id, rating, body, images, reply, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, customer_id, rating, body, images, reply, status, created_at
`

type InsertReviewParams struct {
	ID         uuid.UUID    `json:"id"`
	ProductID  uuid.UUID    `json:"productId"`
	CustomerID pgtype.UUID  `json:"customerId"`
	Rating     int16        `json:"rating"`
	Body       string       `json:"body"`
	Images     []byte       `json:"images"`
	Reply      []byte       `json:"reply"`
	Status     ReviewStatus `json:"status"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.ID,
		arg.ProductID,
		arg.CustomerID,
		arg.Rating,
		arg.Body,
		arg.Images,
		arg.Reply,
		arg.Status,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CustomerID,
		&i.Rating,
		&i.Body,
		&i.Images,
		&i.Reply,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listColorsByProduct = `-- name: ListColorsByProduct :many
SELECT id, product_id, name, hex, available, price_delta FROM colors WHERE product_id = $1 ORDER BY name
`

func (q *Queries) ListColorsByProduct(ctx context.Context, productID uuid.UUID) ([]Color, error) {
	rows, err := q.db.Query(ctx, listColorsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Color
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Hex,
			&i.Available,
			&i.PriceDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByProduct = `-- name: ListOptionsByProduct :many
SELECT id, product_id, label, description, type, price_delta, max_chars FROM options WHERE product_id = $1 ORDER BY label
`

func (q *Queries) ListOptionsByProduct(ctx context.Context, productID uuid.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Label,
			&i.Description,
			&i.Type,
			&i.PriceDelta,
			&i.MaxChars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByStatus = `-- name: ListProductsByStatus :many
SELECT id, slug, name, description, category_id, base_price, dimensions, material, model3d_url, images, status, rating_avg, review_count, created_at FROM products WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProductsByStatus(ctx context.Context, status ProductStatus) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.BasePrice,
			&i.Dimensions,
			&i.Material,
			&i.Model3dUrl,
			&i.Images,
			&i.Status,
			&i.RatingAvg,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
