// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteAuxCost = `-- name: DeleteAuxCost :one
DELETE FROM aux_costs WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteAuxCost(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAuxCost, id)
	err := row.Scan(&id)
	return id, err
}

const deleteMachine = `-- name: DeleteMachine :one
DELETE FROM machines WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteMachine(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteMachine, id)
	err := row.Scan(&id)
	return id, err
}

const insertAuxCost = `-- name: InsertAuxCost :one
INSERT INTO aux_costs (id, label, kind, amount_vnd)
VALUES ($1, $2, $3, $4)
RETURNING id, label, kind, amount_vnd, created_at, updated_at
`

type InsertAuxCostParams struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	Kind      string    `json:"kind"`
	AmountVnd int64     `json:"amountVnd"`
}

func (q *Queries) InsertAuxCost(ctx context.Context, arg InsertAuxCostParams) (AuxCost, error) {
	row := q.db.QueryRow(ctx, insertAuxCost,
		arg.ID,
		arg.Label,
		arg.Kind,
		arg.AmountVnd,
	)
	var i AuxCost
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Kind,
		&i.AmountVnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMachine = `-- name: InsertMachine :one

INSERT INTO machines (id, name, purchase_price_vnd, depreciation_months, expected_hours_per_month, is_primary, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, purchase_price_vnd, depreciation_months, expected_hours_per_month, is_primary, active, created_at, updated_at
`

type InsertMachineParams struct {
	ID                    uuid.UUID `json:"id"`
	Name                  string    `json:"name"`
	PurchasePriceVnd      int64     `json:"purchasePriceVnd"`
	DepreciationMonths    int32     `json:"depreciationMonths"`
	ExpectedHoursPerMonth int32     `json:"expectedHoursPerMonth"`
	IsPrimary             bool      `json:"isPrimary"`
	Active                bool      `json:"active"`
}

// costing.sql — Vật tư cost inputs (ADR-039 slice 4c-1): machines (depreciation) + aux_costs (overhead).
// Plain CRUD — the ₫/hour rate and the per-order aux allocation are DERIVED downstream (Go DTO / the 4c-2
// rollup), never stored (ADR-039 pt 8), so these queries carry no money math. Scrap has no table here (it is
// a filament_consumption row, 000019 — the scrap endpoint reuses the deduct helper).
func (q *Queries) InsertMachine(ctx context.Context, arg InsertMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, insertMachine,
		arg.ID,
		arg.Name,
		arg.PurchasePriceVnd,
		arg.DepreciationMonths,
		arg.ExpectedHoursPerMonth,
		arg.IsPrimary,
		arg.Active,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PurchasePriceVnd,
		&i.DepreciationMonths,
		&i.ExpectedHoursPerMonth,
		&i.IsPrimary,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuxCosts = `-- name: ListAuxCosts :many
SELECT id, label, kind, amount_vnd, created_at, updated_at FROM aux_costs ORDER BY kind, label, id
`

// ListAuxCosts returns every overhead line grouped by kind then label — the /vat-tu Chi phí phụ tab (owner+staff).
func (q *Queries) ListAuxCosts(ctx context.Context) ([]AuxCost, error) {
	rows, err := q.db.Query(ctx, listAuxCosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuxCost
	for rows.Next() {
		var i AuxCost
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.AmountVnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachines = `-- name: ListMachines :many
SELECT id, name, purchase_price_vnd, depreciation_months, expected_hours_per_month, is_primary, active, created_at, updated_at FROM machines ORDER BY is_primary DESC, name, id
`

// ListMachines returns every machine, the primary(s) first then by name — the /vat-tu Giờ máy tab (owner+staff).
// The DTO derives ₫/hour = purchase_price_vnd / (depreciation_months × expected_hours_per_month).
func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PurchasePriceVnd,
			&i.DepreciationMonths,
			&i.ExpectedHoursPerMonth,
			&i.IsPrimary,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuxCost = `-- name: UpdateAuxCost :one
UPDATE aux_costs
SET label = $2, kind = $3, amount_vnd = $4, updated_at = now()
WHERE id = $1
RETURNING id, label, kind, amount_vnd, created_at, updated_at
`

type UpdateAuxCostParams struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	Kind      string    `json:"kind"`
	AmountVnd int64     `json:"amountVnd"`
}

func (q *Queries) UpdateAuxCost(ctx context.Context, arg UpdateAuxCostParams) (AuxCost, error) {
	row := q.db.QueryRow(ctx, updateAuxCost,
		arg.ID,
		arg.Label,
		arg.Kind,
		arg.AmountVnd,
	)
	var i AuxCost
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Kind,
		&i.AmountVnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMachine = `-- name: UpdateMachine :one
UPDATE machines
SET name = $2, purchase_price_vnd = $3, depreciation_months = $4, expected_hours_per_month = $5,
    is_primary = $6, active = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, purchase_price_vnd, depreciation_months, expected_hours_per_month, is_primary, active, created_at, updated_at
`

type UpdateMachineParams struct {
	ID                    uuid.UUID `json:"id"`
	Name                  string    `json:"name"`
	PurchasePriceVnd      int64     `json:"purchasePriceVnd"`
	DepreciationMonths    int32     `json:"depreciationMonths"`
	ExpectedHoursPerMonth int32     `json:"expectedHoursPerMonth"`
	IsPrimary             bool      `json:"isPrimary"`
	Active                bool      `json:"active"`
}

func (q *Queries) UpdateMachine(ctx context.Context, arg UpdateMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, updateMachine,
		arg.ID,
		arg.Name,
		arg.PurchasePriceVnd,
		arg.DepreciationMonths,
		arg.ExpectedHoursPerMonth,
		arg.IsPrimary,
		arg.Active,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PurchasePriceVnd,
		&i.DepreciationMonths,
		&i.ExpectedHoursPerMonth,
		&i.IsPrimary,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
