// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, phone, email, social_handle, addresses, created_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, phone, email, social_handle, addresses, created_at FROM customers WHERE phone = $1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
	)
	return i, err
}

const insertConsentGrant = `-- name: InsertConsentGrant :one
INSERT INTO consent_grants (id, customer_id, scope, channel, policy_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, scope, channel, granted_at, policy_version, withdrawn_at
`

type InsertConsentGrantParams struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    uuid.UUID      `json:"customerId"`
	Scope         ConsentScope   `json:"scope"`
	Channel       ConsentChannel `json:"channel"`
	PolicyVersion string         `json:"policyVersion"`
}

// Append a granted purpose. granted_at defaults to now(); withdrawn_at is NULL (active).
func (q *Queries) InsertConsentGrant(ctx context.Context, arg InsertConsentGrantParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, insertConsentGrant,
		arg.ID,
		arg.CustomerID,
		arg.Scope,
		arg.Channel,
		arg.PolicyVersion,
	)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Scope,
		&i.Channel,
		&i.GrantedAt,
		&i.PolicyVersion,
		&i.WithdrawnAt,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :one

INSERT INTO customers (id, name, phone, email, social_handle, addresses)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, phone, email, social_handle, addresses, created_at
`

type InsertCustomerParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Phone        string    `json:"phone"`
	Email        *string   `json:"email"`
	SocialHandle *string   `json:"socialHandle"`
	Addresses    []byte    `json:"addresses"`
}

// customers.sql — customer + PDPL consent queries (PR-2d). spec.md §02 + vn-compliance.
func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.SocialHandle,
		arg.Addresses,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveConsents = `-- name: ListActiveConsents :many
SELECT id, customer_id, scope, channel, granted_at, policy_version, withdrawn_at FROM consent_grants
WHERE customer_id = $1 AND withdrawn_at IS NULL
ORDER BY granted_at
`

func (q *Queries) ListActiveConsents(ctx context.Context, customerID uuid.UUID) ([]ConsentGrant, error) {
	rows, err := q.db.Query(ctx, listActiveConsents, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentGrant
	for rows.Next() {
		var i ConsentGrant
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Scope,
			&i.Channel,
			&i.GrantedAt,
			&i.PolicyVersion,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawConsent = `-- name: WithdrawConsent :exec
UPDATE consent_grants
SET withdrawn_at = now()
WHERE customer_id = $1 AND scope = $2 AND channel = $3 AND withdrawn_at IS NULL
`

type WithdrawConsentParams struct {
	CustomerID uuid.UUID      `json:"customerId"`
	Scope      ConsentScope   `json:"scope"`
	Channel    ConsentChannel `json:"channel"`
}

// Mark the active grant for (customer, scope, channel) as withdrawn. Never deletes the row.
func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error {
	_, err := q.db.Exec(ctx, withdrawConsent, arg.CustomerID, arg.Scope, arg.Channel)
	return err
}
