// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, phone, email, social_handle, addresses, created_at, password_hash FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getCustomerByLoginEmail = `-- name: GetCustomerByLoginEmail :one
SELECT id, name, phone, email, social_handle, addresses, created_at, password_hash FROM customers
WHERE lower(email) = lower($1) AND password_hash IS NOT NULL
`

// GetCustomerByLoginEmail resolves a login (PR-P1-r): only CREDENTIALED customers (password_hash
// NOT NULL) are candidates, matched case-insensitively on lower(email) — the exact predicate +
// expression of customers_login_email_uq, so this read rides that index and a guest row (NULL
// credential, possibly duplicate email) can never be logged into.
func (q *Queries) GetCustomerByLoginEmail(ctx context.Context, lower string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByLoginEmail, lower)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, phone, email, social_handle, addresses, created_at, password_hash FROM customers WHERE phone = $1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const insertConsentGrant = `-- name: InsertConsentGrant :one
INSERT INTO consent_grants (id, customer_id, scope, channel, policy_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, scope, channel, granted_at, policy_version, withdrawn_at
`

type InsertConsentGrantParams struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    uuid.UUID      `json:"customerId"`
	Scope         ConsentScope   `json:"scope"`
	Channel       ConsentChannel `json:"channel"`
	PolicyVersion string         `json:"policyVersion"`
}

// Append a granted purpose. granted_at defaults to now(); withdrawn_at is NULL (active).
func (q *Queries) InsertConsentGrant(ctx context.Context, arg InsertConsentGrantParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, insertConsentGrant,
		arg.ID,
		arg.CustomerID,
		arg.Scope,
		arg.Channel,
		arg.PolicyVersion,
	)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Scope,
		&i.Channel,
		&i.GrantedAt,
		&i.PolicyVersion,
		&i.WithdrawnAt,
	)
	return i, err
}

const insertConsentGrantIfAbsent = `-- name: InsertConsentGrantIfAbsent :exec
INSERT INTO consent_grants (id, customer_id, scope, channel, policy_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (customer_id, scope, channel) WHERE withdrawn_at IS NULL DO NOTHING
`

type InsertConsentGrantIfAbsentParams struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    uuid.UUID      `json:"customerId"`
	Scope         ConsentScope   `json:"scope"`
	Channel       ConsentChannel `json:"channel"`
	PolicyVersion string         `json:"policyVersion"`
}

// InsertConsentGrantIfAbsent appends a grant idempotently: if an ACTIVE grant already exists for
// (customer, scope, channel) it does nothing, so a returning customer re-checking-out never trips
// the consent_grants_active_uq partial unique and rolls back their order tx. The ON CONFLICT target
// mirrors that partial index exactly (predicate included) so Postgres can infer it. PDPL: still one
// explicit row per active purpose, never a pre-defaulted boolean; re-grant-after-withdrawal is a new
// row (a withdrawn grant is not "active", so it does not conflict).
func (q *Queries) InsertConsentGrantIfAbsent(ctx context.Context, arg InsertConsentGrantIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertConsentGrantIfAbsent,
		arg.ID,
		arg.CustomerID,
		arg.Scope,
		arg.Channel,
		arg.PolicyVersion,
	)
	return err
}

const insertCustomer = `-- name: InsertCustomer :one

INSERT INTO customers (id, name, phone, email, social_handle, addresses)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, phone, email, social_handle, addresses, created_at, password_hash
`

type InsertCustomerParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Phone        string    `json:"phone"`
	Email        *string   `json:"email"`
	SocialHandle *string   `json:"socialHandle"`
	Addresses    []byte    `json:"addresses"`
}

// customers.sql — customer + PDPL consent queries (PR-2d). spec.md §02 + vn-compliance.
func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.SocialHandle,
		arg.Addresses,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const insertCustomerWithCredential = `-- name: InsertCustomerWithCredential :one
INSERT INTO customers (id, name, phone, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, phone, email, social_handle, addresses, created_at, password_hash
`

type InsertCustomerWithCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Phone        string    `json:"phone"`
	Email        *string   `json:"email"`
	PasswordHash *string   `json:"passwordHash"`
}

// InsertCustomerWithCredential registers a storefront account (PR-P1-r): a customer row that
// carries a login credential. addresses defaults to '[]' and social_handle to NULL (a registrant
// supplies only name/phone/email/password). A duplicate login email is rejected by the
// customers_login_email_uq partial unique index (23505 → 409 in the handler), so there is no
// find-then-insert race — the DB is the single arbiter of login-email uniqueness.
func (q *Queries) InsertCustomerWithCredential(ctx context.Context, arg InsertCustomerWithCredentialParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomerWithCredential,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.SocialHandle,
		&i.Addresses,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listActiveConsents = `-- name: ListActiveConsents :many
SELECT id, customer_id, scope, channel, granted_at, policy_version, withdrawn_at FROM consent_grants
WHERE customer_id = $1 AND withdrawn_at IS NULL
ORDER BY granted_at
`

func (q *Queries) ListActiveConsents(ctx context.Context, customerID uuid.UUID) ([]ConsentGrant, error) {
	rows, err := q.db.Query(ctx, listActiveConsents, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentGrant
	for rows.Next() {
		var i ConsentGrant
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Scope,
			&i.Channel,
			&i.GrantedAt,
			&i.PolicyVersion,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminCustomers = `-- name: ListAdminCustomers :many
SELECT
  c.id, c.name, c.phone, c.email, c.social_handle,
  count(o.id)                        AS order_count,
  coalesce(sum(o.total), 0)::bigint  AS total_spent,
  max(o.created_at)::timestamptz     AS last_order_at
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id
GROUP BY c.id
ORDER BY max(o.created_at) DESC NULLS LAST, c.created_at DESC
`

type ListAdminCustomersRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Phone        string             `json:"phone"`
	Email        *string            `json:"email"`
	SocialHandle *string            `json:"socialHandle"`
	OrderCount   int64              `json:"orderCount"`
	TotalSpent   int64              `json:"totalSpent"`
	LastOrderAt  pgtype.Timestamptz `json:"lastOrderAt"`
}

// ListAdminCustomers rolls every customer up with their order aggregates for the admin Khách hàng
// list (P3-p). LEFT JOIN so a customer with no orders still appears (count 0, spent 0, last NULL).
// Money stays raw int-VND: sum(bigint) is numeric, cast back to bigint (coalesced to 0). Ordered
// most-recently-active first so a customer who just ordered floats to the top; a customer with no
// orders sorts last, then newest customer. NOT paginated — a made-to-order shop's base is small and
// the FE searches the whole set (mirrors the products list).
// ponytail: totalSpent/orderCount count ALL orders regardless of status (rough lifetime value);
// add a `WHERE o.status IN (paid..completed)` if the shop wants strict "tổng chi", and server
// paging + a search predicate if the base ever outgrows a single fetch.
func (q *Queries) ListAdminCustomers(ctx context.Context) ([]ListAdminCustomersRow, error) {
	rows, err := q.db.Query(ctx, listAdminCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminCustomersRow
	for rows.Next() {
		var i ListAdminCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.SocialHandle,
			&i.OrderCount,
			&i.TotalSpent,
			&i.LastOrderAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawConsent = `-- name: WithdrawConsent :exec
UPDATE consent_grants
SET withdrawn_at = now()
WHERE customer_id = $1 AND scope = $2 AND channel = $3 AND withdrawn_at IS NULL
`

type WithdrawConsentParams struct {
	CustomerID uuid.UUID      `json:"customerId"`
	Scope      ConsentScope   `json:"scope"`
	Channel    ConsentChannel `json:"channel"`
}

// Mark the active grant for (customer, scope, channel) as withdrawn. Never deletes the row.
func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error {
	_, err := q.db.Exec(ctx, withdrawConsent, arg.CustomerID, arg.Scope, arg.Channel)
	return err
}
