// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encode_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getEncodeTokenByHash = `-- name: GetEncodeTokenByHash :one
SELECT id, user_id, label, token_hash, scope, created_at, last_used_at, revoked_at FROM encode_tokens WHERE token_hash = $1
`

// The auth-middleware lookup on every request bearing a scoped-token-shaped Bearer credential.
// Unfiltered by revoked_at — the middleware checks revoked_at/scope itself so a revoked token can
// still be told apart from "no such token" (both fail closed the same way to the caller either way).
func (q *Queries) GetEncodeTokenByHash(ctx context.Context, tokenHash string) (EncodeToken, error) {
	row := q.db.QueryRow(ctx, getEncodeTokenByHash, tokenHash)
	var i EncodeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertEncodeToken = `-- name: InsertEncodeToken :one

INSERT INTO encode_tokens (id, user_id, label, token_hash, scope)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, label, token_hash, scope, created_at, last_used_at, revoked_at
`

type InsertEncodeTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	Label     string    `json:"label"`
	TokenHash string    `json:"tokenHash"`
	Scope     string    `json:"scope"`
}

// encode_tokens.sql — scoped Bearer tokens for the NFC-encode-only Shortcuts automation (see
// 000032_encode_tokens.up.sql). Owner-only surface (mirrors staff & roles, users.sql).
func (q *Queries) InsertEncodeToken(ctx context.Context, arg InsertEncodeTokenParams) (EncodeToken, error) {
	row := q.db.QueryRow(ctx, insertEncodeToken,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.TokenHash,
		arg.Scope,
	)
	var i EncodeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listEncodeTokens = `-- name: ListEncodeTokens :many
SELECT id, user_id, label, token_hash, scope, created_at, last_used_at, revoked_at FROM encode_tokens ORDER BY created_at DESC
`

// The token-management list (Cài đặt › NFC Shortcuts). Newest first; token_hash is never projected
// to the handler's wire type (toEncodeToken drops it) — this query still selects * for InsertEncodeToken's
// sibling shape, but the handler never serializes the hash column.
func (q *Queries) ListEncodeTokens(ctx context.Context) ([]EncodeToken, error) {
	rows, err := q.db.Query(ctx, listEncodeTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncodeToken
	for rows.Next() {
		var i EncodeToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.TokenHash,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEncodeToken = `-- name: RevokeEncodeToken :one
UPDATE encode_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, label, token_hash, scope, created_at, last_used_at, revoked_at
`

// Owner-only management (classify → authOwnerOnly), so ANY owner may revoke ANY token — not scoped to
// its creator (a small team's owners jointly administer the Shortcuts credentials). Re-revoking an
// already-revoked (or nonexistent) row returns ErrNotFound via the zero-rows check in
// Identity.RevokeEncodeToken, distinguishing "nothing to revoke" from a genuine write.
func (q *Queries) RevokeEncodeToken(ctx context.Context, id uuid.UUID) (EncodeToken, error) {
	row := q.db.QueryRow(ctx, revokeEncodeToken, id)
	var i EncodeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchEncodeToken = `-- name: TouchEncodeToken :exec
UPDATE encode_tokens SET last_used_at = now() WHERE id = $1
`

// Bumps last_used_at on a successful auth — best-effort observability for "is this Shortcut still
// in use", not a security control.
func (q *Queries) TouchEncodeToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchEncodeToken, id)
	return err
}
