// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filament.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchesToDecrement = `-- name: BatchesToDecrement :many

SELECT id, qty_remaining, qty_original, total_cost_vnd
FROM filament_batches
WHERE material_id = $1 AND qty_remaining > 0
ORDER BY imported_at, id
FOR UPDATE
`

type BatchesToDecrementRow struct {
	ID           uuid.UUID `json:"id"`
	QtyRemaining int64     `json:"qtyRemaining"`
	QtyOriginal  int64     `json:"qtyOriginal"`
	TotalCostVnd int64     `json:"totalCostVnd"`
}

// ── Deduct-on-print (slice 4b, ADR-039 pt 2/4) ────────────────────────────────────────────────────────
// BatchesToDecrement returns a material's OPEN lots oldest-first for a FIFO draw, row-locked (FOR UPDATE)
// so two concurrent deduct-on-print draws of the same filament serialize — the second blocks until the
// first commits, then reads the decremented qty_remaining, so no lost update. qty_original is returned so
// the caller derives each lot's ₫/unit = total_cost_vnd / qty_original when it freezes the FIFO cost.
func (q *Queries) BatchesToDecrement(ctx context.Context, materialID uuid.UUID) ([]BatchesToDecrementRow, error) {
	rows, err := q.db.Query(ctx, batchesToDecrement, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchesToDecrementRow
	for rows.Next() {
		var i BatchesToDecrementRow
		if err := rows.Scan(
			&i.ID,
			&i.QtyRemaining,
			&i.QtyOriginal,
			&i.TotalCostVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const decrementBatch = `-- name: DecrementBatch :exec
UPDATE filament_batches SET qty_remaining = qty_remaining - $1 WHERE id = $2
`

type DecrementBatchParams struct {
	Drawn int64     `json:"drawn"`
	ID    uuid.UUID `json:"id"`
}

// DecrementBatch subtracts a drawn qty from one lot. The 000018 CHECK (qty_remaining >= 0) is the backstop;
// the caller never takes more than the lot's qty_remaining (clamp), so this cannot go negative.
func (q *Queries) DecrementBatch(ctx context.Context, arg DecrementBatchParams) error {
	_, err := q.db.Exec(ctx, decrementBatch, arg.Drawn, arg.ID)
	return err
}

const getFilamentMaterial = `-- name: GetFilamentMaterial :one
SELECT
  m.id, m.name, m.material, m.unit, m.hex, m.low_stock_threshold, m.archived, m.created_at, m.updated_at,
  COALESCE(SUM(b.qty_remaining), 0)::bigint AS stock_qty,
  COALESCE(
    SUM(b.qty_remaining::numeric * b.total_cost_vnd / b.qty_original) / NULLIF(SUM(b.qty_remaining), 0),
    0
  )::float8 AS avg_cost_per_unit
FROM filament_materials m
LEFT JOIN filament_batches b ON b.material_id = m.id
WHERE m.id = $1
GROUP BY m.id
`

type GetFilamentMaterialRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Material          string             `json:"material"`
	Unit              string             `json:"unit"`
	Hex               *string            `json:"hex"`
	LowStockThreshold int64              `json:"lowStockThreshold"`
	Archived          bool               `json:"archived"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	StockQty          int64              `json:"stockQty"`
	AvgCostPerUnit    float64            `json:"avgCostPerUnit"`
}

// GetFilamentMaterial is the by-id read with the same derived stock/avg (LEFT JOIN → exists with no lots
// still returns one row). Batches for the weighted-avg breakdown panel come from ListFilamentBatchesByMaterial.
func (q *Queries) GetFilamentMaterial(ctx context.Context, id uuid.UUID) (GetFilamentMaterialRow, error) {
	row := q.db.QueryRow(ctx, getFilamentMaterial, id)
	var i GetFilamentMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Material,
		&i.Unit,
		&i.Hex,
		&i.LowStockThreshold,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StockQty,
		&i.AvgCostPerUnit,
	)
	return i, err
}

const insertConsumption = `-- name: InsertConsumption :one
INSERT INTO filament_consumption (id, material_id, kind, qty, cost_vnd, order_item_id, product_name, reason, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, material_id, kind, qty, cost_vnd, order_item_id, product_name, reason, note, at
`

type InsertConsumptionParams struct {
	ID          uuid.UUID   `json:"id"`
	MaterialID  uuid.UUID   `json:"materialId"`
	Kind        string      `json:"kind"`
	Qty         int64       `json:"qty"`
	CostVnd     int64       `json:"costVnd"`
	OrderItemID pgtype.UUID `json:"orderItemId"`
	ProductName *string     `json:"productName"`
	Reason      *string     `json:"reason"`
	Note        *string     `json:"note"`
}

// InsertConsumption writes ONE draw-ledger row for the ACTUAL qty drawn (never the requested qty when short).
// cost_vnd is the FIFO actual cost the caller froze (Σ per-lot drawn × ₫/unit, rounded once). order_item_id
// is the printed line (NULL for a scrap draw); product_name is denormalized so the row survives a catalog edit.
func (q *Queries) InsertConsumption(ctx context.Context, arg InsertConsumptionParams) (FilamentConsumption, error) {
	row := q.db.QueryRow(ctx, insertConsumption,
		arg.ID,
		arg.MaterialID,
		arg.Kind,
		arg.Qty,
		arg.CostVnd,
		arg.OrderItemID,
		arg.ProductName,
		arg.Reason,
		arg.Note,
	)
	var i FilamentConsumption
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Kind,
		&i.Qty,
		&i.CostVnd,
		&i.OrderItemID,
		&i.ProductName,
		&i.Reason,
		&i.Note,
		&i.At,
	)
	return i, err
}

const insertFilamentBatch = `-- name: InsertFilamentBatch :one
INSERT INTO filament_batches (id, material_id, qty_original, qty_remaining, total_cost_vnd)
VALUES ($1, $2, $3, $3, $4)
RETURNING id, material_id, imported_at, qty_original, qty_remaining, total_cost_vnd
`

type InsertFilamentBatchParams struct {
	ID           uuid.UUID `json:"id"`
	MaterialID   uuid.UUID `json:"materialId"`
	QtyOriginal  int64     `json:"qtyOriginal"`
	TotalCostVnd int64     `json:"totalCostVnd"`
}

// InsertFilamentBatch records one import lot; qty_remaining starts equal to qty_original (a fresh lot is
// untouched). The handler computes qty_original = spoolCount × qtyPerSpool and total_cost = spoolCount ×
// pricePerSpool from the "nhập cuộn" dialog.
func (q *Queries) InsertFilamentBatch(ctx context.Context, arg InsertFilamentBatchParams) (FilamentBatch, error) {
	row := q.db.QueryRow(ctx, insertFilamentBatch,
		arg.ID,
		arg.MaterialID,
		arg.QtyOriginal,
		arg.TotalCostVnd,
	)
	var i FilamentBatch
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.ImportedAt,
		&i.QtyOriginal,
		&i.QtyRemaining,
		&i.TotalCostVnd,
	)
	return i, err
}

const insertFilamentMaterial = `-- name: InsertFilamentMaterial :one

INSERT INTO filament_materials (id, name, material, unit, hex, low_stock_threshold)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, material, unit, hex, low_stock_threshold, archived, created_at, updated_at
`

type InsertFilamentMaterialParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Material          string    `json:"material"`
	Unit              string    `json:"unit"`
	Hex               *string   `json:"hex"`
	LowStockThreshold int64     `json:"lowStockThreshold"`
}

// filament.sql — Vật tư inventory (ADR-039 slice 4a). filament_materials = shop-wide palette;
// filament_batches = import lots. Stock + weighted-average cost/unit are DERIVED here (never stored): the
// list/get queries LEFT JOIN batches so a never-imported material reads stock 0, avg 0.
func (q *Queries) InsertFilamentMaterial(ctx context.Context, arg InsertFilamentMaterialParams) (FilamentMaterial, error) {
	row := q.db.QueryRow(ctx, insertFilamentMaterial,
		arg.ID,
		arg.Name,
		arg.Material,
		arg.Unit,
		arg.Hex,
		arg.LowStockThreshold,
	)
	var i FilamentMaterial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Material,
		&i.Unit,
		&i.Hex,
		&i.LowStockThreshold,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilamentBatchesByMaterial = `-- name: ListFilamentBatchesByMaterial :many
SELECT id, material_id, imported_at, qty_original, qty_remaining, total_cost_vnd FROM filament_batches WHERE material_id = $1 ORDER BY imported_at, id
`

func (q *Queries) ListFilamentBatchesByMaterial(ctx context.Context, materialID uuid.UUID) ([]FilamentBatch, error) {
	rows, err := q.db.Query(ctx, listFilamentBatchesByMaterial, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilamentBatch
	for rows.Next() {
		var i FilamentBatch
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.ImportedAt,
			&i.QtyOriginal,
			&i.QtyRemaining,
			&i.TotalCostVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilamentMaterials = `-- name: ListFilamentMaterials :many
SELECT
  m.id, m.name, m.material, m.unit, m.hex, m.low_stock_threshold, m.archived, m.created_at, m.updated_at,
  COALESCE(SUM(b.qty_remaining), 0)::bigint AS stock_qty,
  COALESCE(
    SUM(b.qty_remaining::numeric * b.total_cost_vnd / b.qty_original) / NULLIF(SUM(b.qty_remaining), 0),
    0
  )::float8 AS avg_cost_per_unit
FROM filament_materials m
LEFT JOIN filament_batches b ON b.material_id = m.id
WHERE ($1::bool IS TRUE OR m.archived = false)
GROUP BY m.id
ORDER BY m.archived, m.name
`

type ListFilamentMaterialsRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Material          string             `json:"material"`
	Unit              string             `json:"unit"`
	Hex               *string            `json:"hex"`
	LowStockThreshold int64              `json:"lowStockThreshold"`
	Archived          bool               `json:"archived"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	StockQty          int64              `json:"stockQty"`
	AvgCostPerUnit    float64            `json:"avgCostPerUnit"`
}

// ListFilamentMaterials returns the palette with DERIVED stock + weighted-average cost/unit. The weighted
// average is Σ(qty_remaining × per-lot ₫/unit) ÷ Σ(qty_remaining) where per-lot ₫/unit = total_cost/qty_original;
// it is computed in ONE numeric expression (no per-lot pre-rounding → no int-VND drift, ADR-039) and cast
// to float8 for display (a RATE, not stored money — frozen to int only at the print-time snapshot, 4b). A
// material with no batches reads stock 0, avg 0. include_archived NULL → active only (archived hidden).
func (q *Queries) ListFilamentMaterials(ctx context.Context, includeArchived *bool) ([]ListFilamentMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listFilamentMaterials, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilamentMaterialsRow
	for rows.Next() {
		var i ListFilamentMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Material,
			&i.Unit,
			&i.Hex,
			&i.LowStockThreshold,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StockQty,
			&i.AvgCostPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderItemForDeduction = `-- name: OrderItemForDeduction :one
SELECT oi.product_id, oi.color_id, oi.part_colors, oi.quantity,
  p.name AS product_name,
  p.est_filament_qty AS product_est_filament_qty
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.id = $1
`

type OrderItemForDeductionRow struct {
	ProductID             uuid.UUID   `json:"productId"`
	ColorID               pgtype.UUID `json:"colorId"`
	PartColors            []byte      `json:"partColors"`
	Quantity              int32       `json:"quantity"`
	ProductName           string      `json:"productName"`
	ProductEstFilamentQty int64       `json:"productEstFilamentQty"`
}

// OrderItemForDeduction is the deduct-on-print resolution read (ADR-039 pt 4): the line a print job draws
// for — product_id + color_id + the ADR-037 part_colors snapshot + quantity, plus the product's flat est +
// name. product FK is RESTRICT (000005) so the product always resolves. The handler turns this into draw
// lines using the product's live parts/colors (grams from parts.est_filament_qty | products.est_filament_qty,
// material from colors.filament_material_id).
func (q *Queries) OrderItemForDeduction(ctx context.Context, id uuid.UUID) (OrderItemForDeductionRow, error) {
	row := q.db.QueryRow(ctx, orderItemForDeduction, id)
	var i OrderItemForDeductionRow
	err := row.Scan(
		&i.ProductID,
		&i.ColorID,
		&i.PartColors,
		&i.Quantity,
		&i.ProductName,
		&i.ProductEstFilamentQty,
	)
	return i, err
}

const updateFilamentMaterial = `-- name: UpdateFilamentMaterial :one
UPDATE filament_materials
SET name = $2, material = $3, unit = $4, hex = $5, low_stock_threshold = $6, archived = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, material, unit, hex, low_stock_threshold, archived, created_at, updated_at
`

type UpdateFilamentMaterialParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Material          string    `json:"material"`
	Unit              string    `json:"unit"`
	Hex               *string   `json:"hex"`
	LowStockThreshold int64     `json:"lowStockThreshold"`
	Archived          bool      `json:"archived"`
}

func (q *Queries) UpdateFilamentMaterial(ctx context.Context, arg UpdateFilamentMaterialParams) (FilamentMaterial, error) {
	row := q.db.QueryRow(ctx, updateFilamentMaterial,
		arg.ID,
		arg.Name,
		arg.Material,
		arg.Unit,
		arg.Hex,
		arg.LowStockThreshold,
		arg.Archived,
	)
	var i FilamentMaterial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Material,
		&i.Unit,
		&i.Hex,
		&i.LowStockThreshold,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
