// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filament.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFilamentMaterial = `-- name: GetFilamentMaterial :one
SELECT
  m.id, m.name, m.material, m.unit, m.hex, m.low_stock_threshold, m.archived, m.created_at, m.updated_at,
  COALESCE(SUM(b.qty_remaining), 0)::bigint AS stock_qty,
  COALESCE(
    SUM(b.qty_remaining::numeric * b.total_cost_vnd / b.qty_original) / NULLIF(SUM(b.qty_remaining), 0),
    0
  )::float8 AS avg_cost_per_unit
FROM filament_materials m
LEFT JOIN filament_batches b ON b.material_id = m.id
WHERE m.id = $1
GROUP BY m.id
`

type GetFilamentMaterialRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Material          string             `json:"material"`
	Unit              string             `json:"unit"`
	Hex               *string            `json:"hex"`
	LowStockThreshold int64              `json:"lowStockThreshold"`
	Archived          bool               `json:"archived"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	StockQty          int64              `json:"stockQty"`
	AvgCostPerUnit    float64            `json:"avgCostPerUnit"`
}

// GetFilamentMaterial is the by-id read with the same derived stock/avg (LEFT JOIN → exists with no lots
// still returns one row). Batches for the weighted-avg breakdown panel come from ListFilamentBatchesByMaterial.
func (q *Queries) GetFilamentMaterial(ctx context.Context, id uuid.UUID) (GetFilamentMaterialRow, error) {
	row := q.db.QueryRow(ctx, getFilamentMaterial, id)
	var i GetFilamentMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Material,
		&i.Unit,
		&i.Hex,
		&i.LowStockThreshold,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StockQty,
		&i.AvgCostPerUnit,
	)
	return i, err
}

const insertFilamentBatch = `-- name: InsertFilamentBatch :one
INSERT INTO filament_batches (id, material_id, qty_original, qty_remaining, total_cost_vnd)
VALUES ($1, $2, $3, $3, $4)
RETURNING id, material_id, imported_at, qty_original, qty_remaining, total_cost_vnd
`

type InsertFilamentBatchParams struct {
	ID           uuid.UUID `json:"id"`
	MaterialID   uuid.UUID `json:"materialId"`
	QtyOriginal  int64     `json:"qtyOriginal"`
	TotalCostVnd int64     `json:"totalCostVnd"`
}

// InsertFilamentBatch records one import lot; qty_remaining starts equal to qty_original (a fresh lot is
// untouched). The handler computes qty_original = spoolCount × qtyPerSpool and total_cost = spoolCount ×
// pricePerSpool from the "nhập cuộn" dialog.
func (q *Queries) InsertFilamentBatch(ctx context.Context, arg InsertFilamentBatchParams) (FilamentBatch, error) {
	row := q.db.QueryRow(ctx, insertFilamentBatch,
		arg.ID,
		arg.MaterialID,
		arg.QtyOriginal,
		arg.TotalCostVnd,
	)
	var i FilamentBatch
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.ImportedAt,
		&i.QtyOriginal,
		&i.QtyRemaining,
		&i.TotalCostVnd,
	)
	return i, err
}

const insertFilamentMaterial = `-- name: InsertFilamentMaterial :one

INSERT INTO filament_materials (id, name, material, unit, hex, low_stock_threshold)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, material, unit, hex, low_stock_threshold, archived, created_at, updated_at
`

type InsertFilamentMaterialParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Material          string    `json:"material"`
	Unit              string    `json:"unit"`
	Hex               *string   `json:"hex"`
	LowStockThreshold int64     `json:"lowStockThreshold"`
}

// filament.sql — Vật tư inventory (ADR-039 slice 4a). filament_materials = shop-wide palette;
// filament_batches = import lots. Stock + weighted-average cost/unit are DERIVED here (never stored): the
// list/get queries LEFT JOIN batches so a never-imported material reads stock 0, avg 0.
func (q *Queries) InsertFilamentMaterial(ctx context.Context, arg InsertFilamentMaterialParams) (FilamentMaterial, error) {
	row := q.db.QueryRow(ctx, insertFilamentMaterial,
		arg.ID,
		arg.Name,
		arg.Material,
		arg.Unit,
		arg.Hex,
		arg.LowStockThreshold,
	)
	var i FilamentMaterial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Material,
		&i.Unit,
		&i.Hex,
		&i.LowStockThreshold,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilamentBatchesByMaterial = `-- name: ListFilamentBatchesByMaterial :many
SELECT id, material_id, imported_at, qty_original, qty_remaining, total_cost_vnd FROM filament_batches WHERE material_id = $1 ORDER BY imported_at, id
`

func (q *Queries) ListFilamentBatchesByMaterial(ctx context.Context, materialID uuid.UUID) ([]FilamentBatch, error) {
	rows, err := q.db.Query(ctx, listFilamentBatchesByMaterial, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilamentBatch
	for rows.Next() {
		var i FilamentBatch
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.ImportedAt,
			&i.QtyOriginal,
			&i.QtyRemaining,
			&i.TotalCostVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilamentMaterials = `-- name: ListFilamentMaterials :many
SELECT
  m.id, m.name, m.material, m.unit, m.hex, m.low_stock_threshold, m.archived, m.created_at, m.updated_at,
  COALESCE(SUM(b.qty_remaining), 0)::bigint AS stock_qty,
  COALESCE(
    SUM(b.qty_remaining::numeric * b.total_cost_vnd / b.qty_original) / NULLIF(SUM(b.qty_remaining), 0),
    0
  )::float8 AS avg_cost_per_unit
FROM filament_materials m
LEFT JOIN filament_batches b ON b.material_id = m.id
WHERE ($1::bool IS TRUE OR m.archived = false)
GROUP BY m.id
ORDER BY m.archived, m.name
`

type ListFilamentMaterialsRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Material          string             `json:"material"`
	Unit              string             `json:"unit"`
	Hex               *string            `json:"hex"`
	LowStockThreshold int64              `json:"lowStockThreshold"`
	Archived          bool               `json:"archived"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	StockQty          int64              `json:"stockQty"`
	AvgCostPerUnit    float64            `json:"avgCostPerUnit"`
}

// ListFilamentMaterials returns the palette with DERIVED stock + weighted-average cost/unit. The weighted
// average is Σ(qty_remaining × per-lot ₫/unit) ÷ Σ(qty_remaining) where per-lot ₫/unit = total_cost/qty_original;
// it is computed in ONE numeric expression (no per-lot pre-rounding → no int-VND drift, ADR-039) and cast
// to float8 for display (a RATE, not stored money — frozen to int only at the print-time snapshot, 4b). A
// material with no batches reads stock 0, avg 0. include_archived NULL → active only (archived hidden).
func (q *Queries) ListFilamentMaterials(ctx context.Context, includeArchived *bool) ([]ListFilamentMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listFilamentMaterials, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilamentMaterialsRow
	for rows.Next() {
		var i ListFilamentMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Material,
			&i.Unit,
			&i.Hex,
			&i.LowStockThreshold,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StockQty,
			&i.AvgCostPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilamentMaterial = `-- name: UpdateFilamentMaterial :one
UPDATE filament_materials
SET name = $2, material = $3, unit = $4, hex = $5, low_stock_threshold = $6, archived = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, material, unit, hex, low_stock_threshold, archived, created_at, updated_at
`

type UpdateFilamentMaterialParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Material          string    `json:"material"`
	Unit              string    `json:"unit"`
	Hex               *string   `json:"hex"`
	LowStockThreshold int64     `json:"lowStockThreshold"`
	Archived          bool      `json:"archived"`
}

func (q *Queries) UpdateFilamentMaterial(ctx context.Context, arg UpdateFilamentMaterialParams) (FilamentMaterial, error) {
	row := q.db.QueryRow(ctx, updateFilamentMaterial,
		arg.ID,
		arg.Name,
		arg.Material,
		arg.Unit,
		arg.Hex,
		arg.LowStockThreshold,
		arg.Archived,
	)
	var i FilamentMaterial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Material,
		&i.Unit,
		&i.Hex,
		&i.LowStockThreshold,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
