// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetJob = `-- name: CreateAssetJob :one

INSERT INTO asset_jobs (
  id, product_id, job_type, source_model_url, source_version, status
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, job_type, source_model_url, source_version, status, attempts, last_error, created_at, updated_at, completed_at
`

type CreateAssetJobParams struct {
	ID             uuid.UUID      `json:"id"`
	ProductID      uuid.UUID      `json:"productId"`
	JobType        AssetJobType   `json:"jobType"`
	SourceModelUrl string         `json:"sourceModelUrl"`
	SourceVersion  string         `json:"sourceVersion"`
	Status         AssetJobStatus `json:"status"`
}

// jobs.sql — fulfillment/asset job queries (PR-2f). architecture.md §3D-pipeline · spec.md §02.
//
// CreateAssetJob is orchestrated by internal/db/jobs.go CreateAssetJobTx, which ALSO enqueues the
// `asset_job.created` outbox event on the SAME tx (publish-on-commit, ADR-006). print_jobs has no
// emit-seam — the print queue is admin-internal (SSE wiring lands in slice 3). UpdateAssetJobStatus
// is the slice-3 worker-callback write; it is defined now so the lifecycle column set is exercised.
func (q *Queries) CreateAssetJob(ctx context.Context, arg CreateAssetJobParams) (AssetJob, error) {
	row := q.db.QueryRow(ctx, createAssetJob,
		arg.ID,
		arg.ProductID,
		arg.JobType,
		arg.SourceModelUrl,
		arg.SourceVersion,
		arg.Status,
	)
	var i AssetJob
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.JobType,
		&i.SourceModelUrl,
		&i.SourceVersion,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAssetJobByID = `-- name: GetAssetJobByID :one
SELECT id, product_id, job_type, source_model_url, source_version, status, attempts, last_error, created_at, updated_at, completed_at FROM asset_jobs WHERE id = $1
`

func (q *Queries) GetAssetJobByID(ctx context.Context, id uuid.UUID) (AssetJob, error) {
	row := q.db.QueryRow(ctx, getAssetJobByID, id)
	var i AssetJob
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.JobType,
		&i.SourceModelUrl,
		&i.SourceVersion,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPrintJobByID = `-- name: GetPrintJobByID :one
SELECT id, order_item_id, stage, printer, color_name, eta, created_at, updated_at FROM print_jobs WHERE id = $1
`

func (q *Queries) GetPrintJobByID(ctx context.Context, id uuid.UUID) (PrintJob, error) {
	row := q.db.QueryRow(ctx, getPrintJobByID, id)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.Stage,
		&i.Printer,
		&i.ColorName,
		&i.Eta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrintQueueEntry = `-- name: GetPrintQueueEntry :one
SELECT pj.id, pj.stage, pj.printer, pj.color_name, pj.eta,
  o.code AS order_code,
  p.name AS product_name,
  oi.quantity AS quantity
FROM print_jobs pj
JOIN order_items oi ON oi.id = pj.order_item_id
JOIN orders o ON o.id = oi.order_id
JOIN products p ON p.id = oi.product_id
WHERE pj.id = $1
`

type GetPrintQueueEntryRow struct {
	ID          uuid.UUID          `json:"id"`
	Stage       PrintStage         `json:"stage"`
	Printer     *string            `json:"printer"`
	ColorName   *string            `json:"colorName"`
	Eta         pgtype.Timestamptz `json:"eta"`
	OrderCode   string             `json:"orderCode"`
	ProductName string             `json:"productName"`
	Quantity    int32              `json:"quantity"`
}

// GetPrintQueueEntry is the single-card read behind the stage PATCH (P3-f): the same enriched shape as
// ListPrintQueue for one job, so the mutate response and the board list carry one identical card shape.
func (q *Queries) GetPrintQueueEntry(ctx context.Context, id uuid.UUID) (GetPrintQueueEntryRow, error) {
	row := q.db.QueryRow(ctx, getPrintQueueEntry, id)
	var i GetPrintQueueEntryRow
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.Printer,
		&i.ColorName,
		&i.Eta,
		&i.OrderCode,
		&i.ProductName,
		&i.Quantity,
	)
	return i, err
}

const insertPrintJob = `-- name: InsertPrintJob :one
INSERT INTO print_jobs (
  id, order_item_id, stage, printer, color_name, eta
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_item_id, stage, printer, color_name, eta, created_at, updated_at
`

type InsertPrintJobParams struct {
	ID          uuid.UUID          `json:"id"`
	OrderItemID uuid.UUID          `json:"orderItemId"`
	Stage       PrintStage         `json:"stage"`
	Printer     *string            `json:"printer"`
	ColorName   *string            `json:"colorName"`
	Eta         pgtype.Timestamptz `json:"eta"`
}

func (q *Queries) InsertPrintJob(ctx context.Context, arg InsertPrintJobParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, insertPrintJob,
		arg.ID,
		arg.OrderItemID,
		arg.Stage,
		arg.Printer,
		arg.ColorName,
		arg.Eta,
	)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.Stage,
		&i.Printer,
		&i.ColorName,
		&i.Eta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetJobsByProduct = `-- name: ListAssetJobsByProduct :many
SELECT id, product_id, job_type, source_model_url, source_version, status, attempts, last_error, created_at, updated_at, completed_at FROM asset_jobs WHERE product_id = $1 ORDER BY created_at DESC, id DESC
`

// ListAssetJobsByProduct powers the admin product editor's render-status panel (P3-j-b GET
// /admin/products/{id}/asset-jobs): every render/ingest job for one product, newest first so the
// editor shows the latest attempt's status at the top. id breaks created_at ties for stable ordering.
func (q *Queries) ListAssetJobsByProduct(ctx context.Context, productID uuid.UUID) ([]AssetJob, error) {
	rows, err := q.db.Query(ctx, listAssetJobsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetJob
	for rows.Next() {
		var i AssetJob
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.JobType,
			&i.SourceModelUrl,
			&i.SourceVersion,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetJobsByStatus = `-- name: ListAssetJobsByStatus :many
SELECT id, product_id, job_type, source_model_url, source_version, status, attempts, last_error, created_at, updated_at, completed_at FROM asset_jobs WHERE status = $1 ORDER BY created_at
`

func (q *Queries) ListAssetJobsByStatus(ctx context.Context, status AssetJobStatus) ([]AssetJob, error) {
	rows, err := q.db.Query(ctx, listAssetJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetJob
	for rows.Next() {
		var i AssetJob
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.JobType,
			&i.SourceModelUrl,
			&i.SourceVersion,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintJobsByStage = `-- name: ListPrintJobsByStage :many
SELECT id, order_item_id, stage, printer, color_name, eta, created_at, updated_at FROM print_jobs WHERE stage = $1 ORDER BY created_at
`

func (q *Queries) ListPrintJobsByStage(ctx context.Context, stage PrintStage) ([]PrintJob, error) {
	rows, err := q.db.Query(ctx, listPrintJobsByStage, stage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrintJob
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.Stage,
			&i.Printer,
			&i.ColorName,
			&i.Eta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintQueue = `-- name: ListPrintQueue :many
SELECT pj.id, pj.stage, pj.printer, pj.color_name, pj.eta,
  o.code AS order_code,
  p.name AS product_name,
  oi.quantity AS quantity
FROM print_jobs pj
JOIN order_items oi ON oi.id = pj.order_item_id
JOIN orders o ON o.id = oi.order_id
JOIN products p ON p.id = oi.product_id
ORDER BY pj.stage, pj.created_at
`

type ListPrintQueueRow struct {
	ID          uuid.UUID          `json:"id"`
	Stage       PrintStage         `json:"stage"`
	Printer     *string            `json:"printer"`
	ColorName   *string            `json:"colorName"`
	Eta         pgtype.Timestamptz `json:"eta"`
	OrderCode   string             `json:"orderCode"`
	ProductName string             `json:"productName"`
	Quantity    int32              `json:"quantity"`
}

// ListPrintQueue is the admin kanban board read (P3-f): every print job across all stages, joined to
// the human-readable order code + product name + quantity so a queue card says WHAT TO MAKE for WHICH
// order (the bare print_jobs row carries ids only, useless at the printer). color_name is denormalized
// on print_jobs (queue-card field, spec §02) so no colors join is needed; printer/eta/color_name are
// nullable. All joins are INNER: a print job's order_item FK is ON DELETE CASCADE and its product FK is
// RESTRICT, so every job has exactly one live item → order + product. Ordered by stage (enum definition
// order NEED_PRINT→SHIPPED) then created_at, so each column is stable FIFO; the client groups by stage.
// ponytail: no pagination — the active print queue on a one-shop box is small; SHIPPED accretes, so add
// a "recent N" / archive filter here if that column ever grows unbounded.
func (q *Queries) ListPrintQueue(ctx context.Context) ([]ListPrintQueueRow, error) {
	rows, err := q.db.Query(ctx, listPrintQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrintQueueRow
	for rows.Next() {
		var i ListPrintQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.Stage,
			&i.Printer,
			&i.ColorName,
			&i.Eta,
			&i.OrderCode,
			&i.ProductName,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetJobStatus = `-- name: UpdateAssetJobStatus :one
UPDATE asset_jobs
SET status = $1,
    attempts = $2,
    last_error = $3,
    completed_at = COALESCE($4, completed_at),
    updated_at = now()
WHERE id = $5
RETURNING id, product_id, job_type, source_model_url, source_version, status, attempts, last_error, created_at, updated_at, completed_at
`

type UpdateAssetJobStatusParams struct {
	Status      AssetJobStatus     `json:"status"`
	Attempts    int32              `json:"attempts"`
	LastError   *string            `json:"lastError"`
	CompletedAt pgtype.Timestamptz `json:"completedAt"`
	ID          uuid.UUID          `json:"id"`
}

// UpdateAssetJobStatus records a worker lifecycle transition (slice-3 callback): the new status,
// the attempt count, last_error (set on 'failed', NULL clears it on 'ready'), and completed_at when
// supplied (COALESCE keeps the prior value when the narg is NULL).
func (q *Queries) UpdateAssetJobStatus(ctx context.Context, arg UpdateAssetJobStatusParams) (AssetJob, error) {
	row := q.db.QueryRow(ctx, updateAssetJobStatus,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.CompletedAt,
		arg.ID,
	)
	var i AssetJob
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.JobType,
		&i.SourceModelUrl,
		&i.SourceVersion,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePrintJobStage = `-- name: UpdatePrintJobStage :one
UPDATE print_jobs
SET stage = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, order_item_id, stage, printer, color_name, eta, created_at, updated_at
`

type UpdatePrintJobStageParams struct {
	Stage PrintStage `json:"stage"`
	ID    uuid.UUID  `json:"id"`
}

// UpdatePrintJobStage advances the print queue stage (staff drag-drop) and refreshes updated_at.
func (q *Queries) UpdatePrintJobStage(ctx context.Context, arg UpdatePrintJobStageParams) (PrintJob, error) {
	row := q.db.QueryRow(ctx, updatePrintJobStage, arg.Stage, arg.ID)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.Stage,
		&i.Printer,
		&i.ColorName,
		&i.Eta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
