// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/huongnguyenduc/lumin-studio/services/core-api/internal/order"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetJobStatus string

const (
	AssetJobStatusQueued     AssetJobStatus = "queued"
	AssetJobStatusProcessing AssetJobStatus = "processing"
	AssetJobStatusReady      AssetJobStatus = "ready"
	AssetJobStatusFailed     AssetJobStatus = "failed"
)

func (e *AssetJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetJobStatus(s)
	case string:
		*e = AssetJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetJobStatus: %T", src)
	}
	return nil
}

type NullAssetJobStatus struct {
	AssetJobStatus AssetJobStatus `json:"assetJobStatus"`
	Valid          bool           `json:"valid"` // Valid is true if AssetJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetJobStatus), nil
}

type AssetJobType string

const (
	AssetJobTypeModelIngest  AssetJobType = "model_ingest"
	AssetJobTypeSpriteRender AssetJobType = "sprite_render"
)

func (e *AssetJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetJobType(s)
	case string:
		*e = AssetJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetJobType: %T", src)
	}
	return nil
}

type NullAssetJobType struct {
	AssetJobType AssetJobType `json:"assetJobType"`
	Valid        bool         `json:"valid"` // Valid is true if AssetJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetJobType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetJobType), nil
}

type ConsentChannel string

const (
	ConsentChannelWeb       ConsentChannel = "web"
	ConsentChannelInbox     ConsentChannel = "inbox"
	ConsentChannelZalo      ConsentChannel = "zalo"
	ConsentChannelExtension ConsentChannel = "extension"
)

func (e *ConsentChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentChannel(s)
	case string:
		*e = ConsentChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentChannel: %T", src)
	}
	return nil
}

type NullConsentChannel struct {
	ConsentChannel ConsentChannel `json:"consentChannel"`
	Valid          bool           `json:"valid"` // Valid is true if ConsentChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentChannel), nil
}

type ConsentScope string

const (
	ConsentScopeMarketing        ConsentScope = "marketing"
	ConsentScopeOrderFulfillment ConsentScope = "order_fulfillment"
	ConsentScopeAnalytics        ConsentScope = "analytics"
	ConsentScopeSessionReplay    ConsentScope = "session_replay"
)

func (e *ConsentScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentScope(s)
	case string:
		*e = ConsentScope(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentScope: %T", src)
	}
	return nil
}

type NullConsentScope struct {
	ConsentScope ConsentScope `json:"consentScope"`
	Valid        bool         `json:"valid"` // Valid is true if ConsentScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentScope) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentScope), nil
}

type OptionType string

const (
	OptionTypeText   OptionType = "text"
	OptionTypeChoice OptionType = "choice"
)

func (e *OptionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OptionType(s)
	case string:
		*e = OptionType(s)
	default:
		return fmt.Errorf("unsupported scan type for OptionType: %T", src)
	}
	return nil
}

type NullOptionType struct {
	OptionType OptionType `json:"optionType"`
	Valid      bool       `json:"valid"` // Valid is true if OptionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOptionType) Scan(value interface{}) error {
	if value == nil {
		ns.OptionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OptionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOptionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OptionType), nil
}

type OrderChannel string

const (
	OrderChannelWeb   OrderChannel = "web"
	OrderChannelInbox OrderChannel = "inbox"
)

func (e *OrderChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderChannel(s)
	case string:
		*e = OrderChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderChannel: %T", src)
	}
	return nil
}

type NullOrderChannel struct {
	OrderChannel OrderChannel `json:"orderChannel"`
	Valid        bool         `json:"valid"` // Valid is true if OrderChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderChannel) Scan(value interface{}) error {
	if value == nil {
		ns.OrderChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderChannel), nil
}

type OrderStatus string

const (
	OrderStatusPENDINGCONFIRM OrderStatus = "PENDING_CONFIRM"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusPRINTING       OrderStatus = "PRINTING"
	OrderStatusSHIPPING       OrderStatus = "SHIPPING"
	OrderStatusCOMPLETED      OrderStatus = "COMPLETED"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
	OrderStatusREFUNDED       OrderStatus = "REFUNDED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"orderStatus"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodBankTransfer PaymentMethod = "bank_transfer"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"paymentMethod"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PrintStage string

const (
	PrintStageNEEDPRINT PrintStage = "NEED_PRINT"
	PrintStagePRINTING  PrintStage = "PRINTING"
	PrintStagePACKING   PrintStage = "PACKING"
	PrintStageSHIPPED   PrintStage = "SHIPPED"
)

func (e *PrintStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrintStage(s)
	case string:
		*e = PrintStage(s)
	default:
		return fmt.Errorf("unsupported scan type for PrintStage: %T", src)
	}
	return nil
}

type NullPrintStage struct {
	PrintStage PrintStage `json:"printStage"`
	Valid      bool       `json:"valid"` // Valid is true if PrintStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrintStage) Scan(value interface{}) error {
	if value == nil {
		ns.PrintStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrintStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrintStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrintStage), nil
}

type ProductStatus string

const (
	ProductStatusActive   ProductStatus = "active"
	ProductStatusDraft    ProductStatus = "draft"
	ProductStatusArchived ProductStatus = "archived"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"productStatus"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type ReviewStatus string

const (
	ReviewStatusPublished ReviewStatus = "published"
	ReviewStatusHidden    ReviewStatus = "hidden"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"reviewStatus"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type UserRole string

const (
	UserRoleOwner UserRole = "owner"
	UserRoleStaff UserRole = "staff"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AssetJob struct {
	ID             uuid.UUID          `json:"id"`
	ProductID      uuid.UUID          `json:"productId"`
	JobType        AssetJobType       `json:"jobType"`
	SourceModelUrl string             `json:"sourceModelUrl"`
	SourceVersion  string             `json:"sourceVersion"`
	Status         AssetJobStatus     `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      *string            `json:"lastError"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	CompletedAt    pgtype.Timestamptz `json:"completedAt"`
}

type Category struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

type Color struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"productId"`
	Name       string    `json:"name"`
	Hex        string    `json:"hex"`
	Available  bool      `json:"available"`
	PriceDelta int64     `json:"priceDelta"`
}

type ConsentGrant struct {
	ID            uuid.UUID          `json:"id"`
	CustomerID    uuid.UUID          `json:"customerId"`
	Scope         ConsentScope       `json:"scope"`
	Channel       ConsentChannel     `json:"channel"`
	GrantedAt     pgtype.Timestamptz `json:"grantedAt"`
	PolicyVersion string             `json:"policyVersion"`
	WithdrawnAt   pgtype.Timestamptz `json:"withdrawnAt"`
}

type Customer struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Phone        string             `json:"phone"`
	Email        *string            `json:"email"`
	SocialHandle *string            `json:"socialHandle"`
	Addresses    []byte             `json:"addresses"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type Option struct {
	ID          uuid.UUID  `json:"id"`
	ProductID   uuid.UUID  `json:"productId"`
	Label       string     `json:"label"`
	Description string     `json:"description"`
	Type        OptionType `json:"type"`
	PriceDelta  int64      `json:"priceDelta"`
	MaxChars    *int32     `json:"maxChars"`
}

type Order struct {
	ID                 uuid.UUID           `json:"id"`
	Code               string              `json:"code"`
	Channel            order.Channel       `json:"channel"`
	Status             order.Status        `json:"status"`
	CustomerID         uuid.UUID           `json:"customerId"`
	ShippingAddress    order.Address       `json:"shippingAddress"`
	Subtotal           int64               `json:"subtotal"`
	ShippingFee        int64               `json:"shippingFee"`
	Total              int64               `json:"total"`
	PaymentMethod      PaymentMethod       `json:"paymentMethod"`
	PaymentProofUrl    *string             `json:"paymentProofUrl"`
	PaymentConfirmedAt pgtype.Timestamptz  `json:"paymentConfirmedAt"`
	RefundProofUrl     *string             `json:"refundProofUrl"`
	TrackingCode       *string             `json:"trackingCode"`
	Note               *string             `json:"note"`
	StatusHistory      []order.StatusEvent `json:"statusHistory"`
	CreatedAt          pgtype.Timestamptz  `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz  `json:"updatedAt"`
}

type OrderItem struct {
	ID              uuid.UUID              `json:"id"`
	OrderID         uuid.UUID              `json:"orderId"`
	ProductID       uuid.UUID              `json:"productId"`
	ColorID         pgtype.UUID            `json:"colorId"`
	OptionIds       []byte                 `json:"optionIds"`
	Personalization *order.Personalization `json:"personalization"`
	Quantity        int32                  `json:"quantity"`
	UnitPrice       int64                  `json:"unitPrice"`
}

type Outbox struct {
	ID            uuid.UUID          `json:"id"`
	Seq           int64              `json:"seq"`
	AggregateType string             `json:"aggregateType"`
	AggregateID   uuid.UUID          `json:"aggregateId"`
	EventType     string             `json:"eventType"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	DedupKey      string             `json:"dedupKey"`
	Attempts      int32              `json:"attempts"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	PublishedAt   pgtype.Timestamptz `json:"publishedAt"`
}

type PrintJob struct {
	ID          uuid.UUID          `json:"id"`
	OrderItemID uuid.UUID          `json:"orderItemId"`
	Stage       PrintStage         `json:"stage"`
	Printer     *string            `json:"printer"`
	ColorName   *string            `json:"colorName"`
	Eta         pgtype.Timestamptz `json:"eta"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Product struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CategoryID  uuid.UUID          `json:"categoryId"`
	BasePrice   int64              `json:"basePrice"`
	Dimensions  []byte             `json:"dimensions"`
	Material    string             `json:"material"`
	Model3dUrl  string             `json:"model3dUrl"`
	Images      []byte             `json:"images"`
	Status      ProductStatus      `json:"status"`
	RatingAvg   *float32           `json:"ratingAvg"`
	ReviewCount int32              `json:"reviewCount"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type ReplyTemplate struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Variables []byte             `json:"variables"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Review struct {
	ID         uuid.UUID          `json:"id"`
	ProductID  uuid.UUID          `json:"productId"`
	CustomerID pgtype.UUID        `json:"customerId"`
	Rating     int16              `json:"rating"`
	Body       string             `json:"body"`
	Images     []byte             `json:"images"`
	Reply      []byte             `json:"reply"`
	Status     ReviewStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Setting struct {
	ID            bool               `json:"id"`
	ShopInfo      []byte             `json:"shopInfo"`
	BankAccount   []byte             `json:"bankAccount"`
	ShippingRules []byte             `json:"shippingRules"`
	RefundPolicy  string             `json:"refundPolicy"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type SettingBankAudit struct {
	ID          uuid.UUID          `json:"id"`
	Seq         int64              `json:"seq"`
	ChangedBy   uuid.UUID          `json:"changedBy"`
	BankAccount []byte             `json:"bankAccount"`
	Reason      *string            `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Role         UserRole  `json:"role"`
	Active       bool      `json:"active"`
	PasswordHash *string   `json:"passwordHash"`
}
