// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConsentChannel string

const (
	ConsentChannelWeb       ConsentChannel = "web"
	ConsentChannelInbox     ConsentChannel = "inbox"
	ConsentChannelZalo      ConsentChannel = "zalo"
	ConsentChannelExtension ConsentChannel = "extension"
)

func (e *ConsentChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentChannel(s)
	case string:
		*e = ConsentChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentChannel: %T", src)
	}
	return nil
}

type NullConsentChannel struct {
	ConsentChannel ConsentChannel `json:"consentChannel"`
	Valid          bool           `json:"valid"` // Valid is true if ConsentChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentChannel), nil
}

type ConsentScope string

const (
	ConsentScopeMarketing        ConsentScope = "marketing"
	ConsentScopeOrderFulfillment ConsentScope = "order_fulfillment"
	ConsentScopeAnalytics        ConsentScope = "analytics"
	ConsentScopeSessionReplay    ConsentScope = "session_replay"
)

func (e *ConsentScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentScope(s)
	case string:
		*e = ConsentScope(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentScope: %T", src)
	}
	return nil
}

type NullConsentScope struct {
	ConsentScope ConsentScope `json:"consentScope"`
	Valid        bool         `json:"valid"` // Valid is true if ConsentScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentScope) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentScope), nil
}

type OptionType string

const (
	OptionTypeText   OptionType = "text"
	OptionTypeChoice OptionType = "choice"
)

func (e *OptionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OptionType(s)
	case string:
		*e = OptionType(s)
	default:
		return fmt.Errorf("unsupported scan type for OptionType: %T", src)
	}
	return nil
}

type NullOptionType struct {
	OptionType OptionType `json:"optionType"`
	Valid      bool       `json:"valid"` // Valid is true if OptionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOptionType) Scan(value interface{}) error {
	if value == nil {
		ns.OptionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OptionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOptionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OptionType), nil
}

type OrderChannel string

const (
	OrderChannelWeb   OrderChannel = "web"
	OrderChannelInbox OrderChannel = "inbox"
)

func (e *OrderChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderChannel(s)
	case string:
		*e = OrderChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderChannel: %T", src)
	}
	return nil
}

type NullOrderChannel struct {
	OrderChannel OrderChannel `json:"orderChannel"`
	Valid        bool         `json:"valid"` // Valid is true if OrderChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderChannel) Scan(value interface{}) error {
	if value == nil {
		ns.OrderChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderChannel), nil
}

type OrderStatus string

const (
	OrderStatusPENDINGCONFIRM OrderStatus = "PENDING_CONFIRM"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusPRINTING       OrderStatus = "PRINTING"
	OrderStatusSHIPPING       OrderStatus = "SHIPPING"
	OrderStatusCOMPLETED      OrderStatus = "COMPLETED"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
	OrderStatusREFUNDED       OrderStatus = "REFUNDED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"orderStatus"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodBankTransfer PaymentMethod = "bank_transfer"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"paymentMethod"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PrintStage string

const (
	PrintStageNEEDPRINT PrintStage = "NEED_PRINT"
	PrintStagePRINTING  PrintStage = "PRINTING"
	PrintStagePACKING   PrintStage = "PACKING"
	PrintStageSHIPPED   PrintStage = "SHIPPED"
)

func (e *PrintStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrintStage(s)
	case string:
		*e = PrintStage(s)
	default:
		return fmt.Errorf("unsupported scan type for PrintStage: %T", src)
	}
	return nil
}

type NullPrintStage struct {
	PrintStage PrintStage `json:"printStage"`
	Valid      bool       `json:"valid"` // Valid is true if PrintStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrintStage) Scan(value interface{}) error {
	if value == nil {
		ns.PrintStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrintStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrintStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrintStage), nil
}

type ProductStatus string

const (
	ProductStatusActive   ProductStatus = "active"
	ProductStatusDraft    ProductStatus = "draft"
	ProductStatusArchived ProductStatus = "archived"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"productStatus"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type ReviewStatus string

const (
	ReviewStatusPublished ReviewStatus = "published"
	ReviewStatusHidden    ReviewStatus = "hidden"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"reviewStatus"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type UserRole string

const (
	UserRoleOwner UserRole = "owner"
	UserRoleStaff UserRole = "staff"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Outbox struct {
	ID            uuid.UUID          `json:"id"`
	Seq           int64              `json:"seq"`
	AggregateType string             `json:"aggregateType"`
	AggregateID   uuid.UUID          `json:"aggregateId"`
	EventType     string             `json:"eventType"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	DedupKey      string             `json:"dedupKey"`
	Attempts      int32              `json:"attempts"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	PublishedAt   pgtype.Timestamptz `json:"publishedAt"`
}
