// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/huongnguyenduc/lumin-studio/services/core-api/internal/order"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
  id, code, channel, status, customer_id, shipping_address,
  subtotal, shipping_fee, total, payment_proof_url, payment_confirmed_at, note, status_history
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at
`

type CreateOrderParams struct {
	ID                 uuid.UUID           `json:"id"`
	Code               string              `json:"code"`
	Channel            order.Channel       `json:"channel"`
	Status             order.Status        `json:"status"`
	CustomerID         uuid.UUID           `json:"customerId"`
	ShippingAddress    order.Address       `json:"shippingAddress"`
	Subtotal           int64               `json:"subtotal"`
	ShippingFee        int64               `json:"shippingFee"`
	Total              int64               `json:"total"`
	PaymentProofUrl    *string             `json:"paymentProofUrl"`
	PaymentConfirmedAt pgtype.Timestamptz  `json:"paymentConfirmedAt"`
	Note               *string             `json:"note"`
	StatusHistory      []order.StatusEvent `json:"statusHistory"`
}

// orders.sql — order spine read/write queries (PR-2e). spec.md §02/§04.
//
// The seams in internal/db/orders.go orchestrate these inside the caller's transaction so the
// domain row, the statusHistory append and the outbox event commit as one unit (ADR-006).
// payment_method is intentionally NOT a CreateOrder param — phase 1 is bank_transfer only, so
// the column DEFAULT supplies it; add the param when a second method arrives.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Code,
		arg.Channel,
		arg.Status,
		arg.CustomerID,
		arg.ShippingAddress,
		arg.Subtotal,
		arg.ShippingFee,
		arg.Total,
		arg.PaymentProofUrl,
		arg.PaymentConfirmedAt,
		arg.Note,
		arg.StatusHistory,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByCode = `-- name: GetOrderByCode :one
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at FROM orders WHERE code = $1
`

func (q *Queries) GetOrderByCode(ctx context.Context, code string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCode, code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at FROM orders WHERE id = $1 FOR UPDATE
`

// GetOrderForUpdate locks the row for the duration of the caller's tx so a status flip reads
// and writes the order atomically (no lost-update race between concurrent transitions).
func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :one
INSERT INTO order_items (
  id, order_id, product_id, color_id, option_ids, personalization, quantity, unit_price
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, order_id, product_id, color_id, option_ids, personalization, quantity, unit_price
`

type InsertOrderItemParams struct {
	ID              uuid.UUID              `json:"id"`
	OrderID         uuid.UUID              `json:"orderId"`
	ProductID       uuid.UUID              `json:"productId"`
	ColorID         pgtype.UUID            `json:"colorId"`
	OptionIds       []byte                 `json:"optionIds"`
	Personalization *order.Personalization `json:"personalization"`
	Quantity        int32                  `json:"quantity"`
	UnitPrice       int64                  `json:"unitPrice"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, insertOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ColorID,
		arg.OptionIds,
		arg.Personalization,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ColorID,
		&i.OptionIds,
		&i.Personalization,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, color_id, option_ids, personalization, quantity, unit_price FROM order_items WHERE order_id = $1
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ColorID,
			&i.OptionIds,
			&i.Personalization,
			&i.Quantity,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at FROM orders WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByStatus(ctx context.Context, status order.Status) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Channel,
			&i.Status,
			&i.CustomerID,
			&i.ShippingAddress,
			&i.Subtotal,
			&i.ShippingFee,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentProofUrl,
			&i.PaymentConfirmedAt,
			&i.RefundProofUrl,
			&i.TrackingCode,
			&i.Note,
			&i.StatusHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1,
    status_history = $2,
    refund_proof_url = COALESCE($3, refund_proof_url),
    payment_confirmed_at = COALESCE($4, payment_confirmed_at),
    updated_at = now()
WHERE id = $5
RETURNING id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	Status             order.Status        `json:"status"`
	StatusHistory      []order.StatusEvent `json:"statusHistory"`
	RefundProofUrl     *string             `json:"refundProofUrl"`
	PaymentConfirmedAt pgtype.Timestamptz  `json:"paymentConfirmedAt"`
	ID                 uuid.UUID           `json:"id"`
}

// UpdateOrderStatus persists a transition: the new status, the full appended statusHistory,
// and — only when supplied — the denormalized refund_proof_url and payment_confirmed_at
// (COALESCE keeps the existing value when the narg is NULL). The append itself is computed in
// Go by order.Transition; this statement just writes the result in one UPDATE.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus,
		arg.Status,
		arg.StatusHistory,
		arg.RefundProofUrl,
		arg.PaymentConfirmedAt,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
