// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/huongnguyenduc/lumin-studio/services/core-api/internal/order"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearOrderPaymentProof = `-- name: ClearOrderPaymentProof :exec
UPDATE orders
SET payment_proof_url = NULL, updated_at = now()
WHERE id = $1 AND payment_proof_url IS NOT NULL
`

// ClearOrderPaymentProof nulls the receipt reference after its Garage object has been deleted
// (ADR-035 retention). The payment_proof_url IS NOT NULL guard makes a re-run a no-op, so a sweep
// that deletes the object but crashes before clearing simply retries idempotently next pass.
func (q *Queries) ClearOrderPaymentProof(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearOrderPaymentProof, id)
	return err
}

const countAdminOrders = `-- name: CountAdminOrders :one
SELECT count(*) FROM orders o
WHERE $1::order_status IS NULL OR o.status = $1::order_status
`

// CountAdminOrders is the total for the admin list envelope — the SAME status filter as ListAdminOrders,
// no sort/limit. It runs as a second autocommit read alongside the list; a concurrent order write between
// the two can skew the count by one (cosmetic, self-heals next request, never a money value), which a
// one-shop admin accepts rather than pay for a snapshot tx (same stance as CountActiveProducts).
func (q *Queries) CountAdminOrders(ctx context.Context, status NullOrderStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminOrders, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
  id, code, channel, status, customer_id, shipping_address,
  subtotal, shipping_fee, total, payment_proof_url, payment_confirmed_at, note, status_history
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url
`

type CreateOrderParams struct {
	ID                 uuid.UUID           `json:"id"`
	Code               string              `json:"code"`
	Channel            order.Channel       `json:"channel"`
	Status             order.Status        `json:"status"`
	CustomerID         uuid.UUID           `json:"customerId"`
	ShippingAddress    order.Address       `json:"shippingAddress"`
	Subtotal           int64               `json:"subtotal"`
	ShippingFee        int64               `json:"shippingFee"`
	Total              int64               `json:"total"`
	PaymentProofUrl    *string             `json:"paymentProofUrl"`
	PaymentConfirmedAt pgtype.Timestamptz  `json:"paymentConfirmedAt"`
	Note               *string             `json:"note"`
	StatusHistory      []order.StatusEvent `json:"statusHistory"`
}

// orders.sql — order spine read/write queries (PR-2e). spec.md §02/§04.
//
// The seams in internal/db/orders.go orchestrate these inside the caller's transaction so the
// domain row, the statusHistory append and the outbox event commit as one unit (ADR-006).
// payment_method is intentionally NOT a CreateOrder param — phase 1 is bank_transfer only, so
// the column DEFAULT supplies it; add the param when a second method arrives.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Code,
		arg.Channel,
		arg.Status,
		arg.CustomerID,
		arg.ShippingAddress,
		arg.Subtotal,
		arg.ShippingFee,
		arg.Total,
		arg.PaymentProofUrl,
		arg.PaymentConfirmedAt,
		arg.Note,
		arg.StatusHistory,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QcPhotoUrl,
	)
	return i, err
}

const getOrderByCode = `-- name: GetOrderByCode :one
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url FROM orders WHERE code = $1
`

func (q *Queries) GetOrderByCode(ctx context.Context, code string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCode, code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QcPhotoUrl,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QcPhotoUrl,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url FROM orders WHERE id = $1 FOR UPDATE
`

// GetOrderForUpdate locks the row for the duration of the caller's tx so a status flip reads
// and writes the order atomically (no lost-update race between concurrent transitions).
func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QcPhotoUrl,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :one
INSERT INTO order_items (
  id, order_id, product_id, color_id, option_ids, personalization, quantity, unit_price,
  part_colors, option_choices
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, order_id, product_id, color_id, option_ids, personalization, quantity, unit_price, part_colors, option_choices
`

type InsertOrderItemParams struct {
	ID              uuid.UUID              `json:"id"`
	OrderID         uuid.UUID              `json:"orderId"`
	ProductID       uuid.UUID              `json:"productId"`
	ColorID         pgtype.UUID            `json:"colorId"`
	OptionIds       []byte                 `json:"optionIds"`
	Personalization *order.Personalization `json:"personalization"`
	Quantity        int32                  `json:"quantity"`
	UnitPrice       int64                  `json:"unitPrice"`
	PartColors      []byte                 `json:"partColors"`
	OptionChoices   []byte                 `json:"optionChoices"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, insertOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ColorID,
		arg.OptionIds,
		arg.Personalization,
		arg.Quantity,
		arg.UnitPrice,
		arg.PartColors,
		arg.OptionChoices,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ColorID,
		&i.OptionIds,
		&i.Personalization,
		&i.Quantity,
		&i.UnitPrice,
		&i.PartColors,
		&i.OptionChoices,
	)
	return i, err
}

const listAdminOrders = `-- name: ListAdminOrders :many
SELECT
  o.id, o.code, c.name AS customer_name, o.channel, o.status, o.total, o.created_at,
  (SELECT p.name
     FROM order_items oi JOIN products p ON p.id = oi.product_id
    WHERE oi.order_id = o.id
    ORDER BY oi.id
    LIMIT 1) AS first_item_name,
  (SELECT count(*) FROM order_items oi WHERE oi.order_id = o.id)::int AS item_count
FROM orders o
JOIN customers c ON c.id = o.customer_id
WHERE $1::order_status IS NULL OR o.status = $1::order_status
ORDER BY o.created_at DESC, o.id DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminOrdersParams struct {
	Status     NullOrderStatus `json:"status"`
	PageOffset int32           `json:"pageOffset"`
	PageLimit  int32           `json:"pageLimit"`
}

type ListAdminOrdersRow struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	CustomerName  string             `json:"customerName"`
	Channel       order.Channel      `json:"channel"`
	Status        order.Status       `json:"status"`
	Total         int64              `json:"total"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	FirstItemName string             `json:"firstItemName"`
	ItemCount     int32              `json:"itemCount"`
}

// ListAdminOrders is the admin orders table read (P3-b, GET /admin/orders): one page of orders newest-
// first, optionally filtered to a single status. Unlike the public timeline it joins the customer NAME
// and, for the "sản phẩm" column, a representative first-item product name + the line-item count (two
// scalar subqueries — bounded per page, backed by order_items_order_idx, no N+1). The first item is
// picked by a stable oi.id order: which line represents a multi-item order carries no meaning, only that
// it is the SAME one every load. The status filter is a nullable narg (NULL = all statuses, "Tất cả").
// created_at DESC, id DESC give a deterministic total order so OFFSET pagination is stable across pages.
// Every order has ≥1 item (CreateOrderTx enforces it) so first_item_name is never NULL in practice.
func (q *Queries) ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]ListAdminOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminOrders, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOrdersRow
	for rows.Next() {
		var i ListAdminOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CustomerName,
			&i.Channel,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.FirstItemName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.color_id, oi.option_ids, oi.personalization, oi.quantity, oi.unit_price, oi.part_colors, oi.option_choices,
  p.name AS product_name,
  c.name AS color_name,
  coalesce(
    (SELECT array_agg(o.label ORDER BY o.label)
       FROM options o
       JOIN jsonb_array_elements_text(oi.option_ids) AS sel(id) ON o.id = sel.id::uuid),
    '{}'
  )::text[] AS option_labels
FROM order_items oi
JOIN products p ON p.id = oi.product_id
LEFT JOIN colors c ON c.id = oi.color_id
WHERE oi.order_id = $1
`

type ListOrderItemsRow struct {
	ID              uuid.UUID              `json:"id"`
	OrderID         uuid.UUID              `json:"orderId"`
	ProductID       uuid.UUID              `json:"productId"`
	ColorID         pgtype.UUID            `json:"colorId"`
	OptionIds       []byte                 `json:"optionIds"`
	Personalization *order.Personalization `json:"personalization"`
	Quantity        int32                  `json:"quantity"`
	UnitPrice       int64                  `json:"unitPrice"`
	PartColors      []byte                 `json:"partColors"`
	OptionChoices   []byte                 `json:"optionChoices"`
	ProductName     string                 `json:"productName"`
	ColorName       *string                `json:"colorName"`
	OptionLabels    []string               `json:"optionLabels"`
}

// ListOrderItems returns an order's line items enriched with the human-readable product name, color
// name and selected option labels (P3-e admin detail) — joined here so the admin order-detail page
// shows WHAT TO MAKE, not raw ids (the merged Order DTO carried ids only, useless to a fulfiller).
// product_name is NOT NULL (product FK is RESTRICT); color_name is NULL when the line has no color;
// option_labels is a text[] (empty, never NULL) whose order is stable-arbitrary (by label), like the
// admin list's first-item pick. The Personalization jsonb is unchanged (oi.*).
func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ColorID,
			&i.OptionIds,
			&i.Personalization,
			&i.Quantity,
			&i.UnitPrice,
			&i.PartColors,
			&i.OptionChoices,
			&i.ProductName,
			&i.ColorName,
			&i.OptionLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url FROM orders WHERE customer_id = $1 ORDER BY created_at DESC
`

// ListOrdersByCustomer returns a customer's own orders, newest-first, for the authenticated
// storefront account history (PR-P1-r, GET /customer/orders). Scoped strictly by customer_id (the
// verified session subject) — never by phone, which is non-unique. Guest orders placed before the
// customer registered are NOT auto-linked (claiming an unverified identity's orders is deferred).
func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Channel,
			&i.Status,
			&i.CustomerID,
			&i.ShippingAddress,
			&i.Subtotal,
			&i.ShippingFee,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentProofUrl,
			&i.PaymentConfirmedAt,
			&i.RefundProofUrl,
			&i.TrackingCode,
			&i.Note,
			&i.StatusHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QcPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url FROM orders WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByStatus(ctx context.Context, status order.Status) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Channel,
			&i.Status,
			&i.CustomerID,
			&i.ShippingAddress,
			&i.Subtotal,
			&i.ShippingFee,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentProofUrl,
			&i.PaymentConfirmedAt,
			&i.RefundProofUrl,
			&i.TrackingCode,
			&i.Note,
			&i.StatusHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QcPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeableProofOrders = `-- name: ListPurgeableProofOrders :many
SELECT id, payment_proof_url
FROM orders
WHERE payment_proof_url IS NOT NULL
  AND status::text = ANY($1::text[])
  AND updated_at < $2
ORDER BY updated_at
LIMIT $3
`

type ListPurgeableProofOrdersParams struct {
	Terminal    []string           `json:"terminal"`
	PurgeBefore pgtype.Timestamptz `json:"purgeBefore"`
	RowLimit    int32              `json:"rowLimit"`
}

type ListPurgeableProofOrdersRow struct {
	ID              uuid.UUID `json:"id"`
	PaymentProofUrl *string   `json:"paymentProofUrl"`
}

// ListPurgeableProofOrders returns orders whose receipt image has outlived the retention window
// (ADR-035): the order is in a terminal status AND its last transition (orders.updated_at, set by
// UpdateOrderStatus and never touched again after a close state) is older than the cutoff. The
// terminal set is passed in from order.TerminalStatuses() so the SQL never hardcodes it. Oldest-first
// + LIMIT bounds one sweep; a nulled row drops out of the payment_proof_url IS NOT NULL filter next
// pass. The retention sweeper deletes each Garage object, then clears the reference.
func (q *Queries) ListPurgeableProofOrders(ctx context.Context, arg ListPurgeableProofOrdersParams) ([]ListPurgeableProofOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurgeableProofOrders, arg.Terminal, arg.PurgeBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurgeableProofOrdersRow
	for rows.Next() {
		var i ListPurgeableProofOrdersRow
		if err := rows.Scan(&i.ID, &i.PaymentProofUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderCode = `-- name: NextOrderCode :one
SELECT nextval('order_code_seq')::bigint AS n
`

// NextOrderCode hands the create tx the next display-code number from order_code_seq (000010).
// nextval is atomic and collision-free across concurrent callers by construction (§6 D9); the Go
// seam formats it as `#LMN-<n>`. Called inside the SAME tx as CreateOrder so a code is minted per
// create attempt (a rolled-back attempt simply burns its number — gaps are expected, codes are
// display handles, not counts).
func (q *Queries) NextOrderCode(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderCode)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const setShippingArtifacts = `-- name: SetShippingArtifacts :one
UPDATE orders
SET tracking_code = $1,
    qc_photo_url = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url
`

type SetShippingArtifactsParams struct {
	TrackingCode *string   `json:"trackingCode"`
	QcPhotoUrl   *string   `json:"qcPhotoUrl"`
	ID           uuid.UUID `json:"id"`
}

// SetShippingArtifacts persists the two mandatory SHIPPING artifacts — the carrier tracking code
// and the QC packing photo (D-P3-6) — on the PRINTING→SHIPPING transition. The status flip itself
// goes through UpdateOrderStatus (order.Transition guard); the transition handler runs this in the
// SAME tx so the flip and its mandatory tracking_code + qc_photo_url (spec §04) commit atomically —
// an order can never reach SHIPPING without both. RETURNING * reflects the new status (already
// flipped in this tx) plus both artifacts (§3h / §6 D12 / P3-e).
func (q *Queries) SetShippingArtifacts(ctx context.Context, arg SetShippingArtifactsParams) (Order, error) {
	row := q.db.QueryRow(ctx, setShippingArtifacts, arg.TrackingCode, arg.QcPhotoUrl, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QcPhotoUrl,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1,
    status_history = $2,
    refund_proof_url = COALESCE($3, refund_proof_url),
    payment_confirmed_at = COALESCE($4, payment_confirmed_at),
    updated_at = now()
WHERE id = $5
RETURNING id, code, channel, status, customer_id, shipping_address, subtotal, shipping_fee, total, payment_method, payment_proof_url, payment_confirmed_at, refund_proof_url, tracking_code, note, status_history, created_at, updated_at, qc_photo_url
`

type UpdateOrderStatusParams struct {
	Status             order.Status        `json:"status"`
	StatusHistory      []order.StatusEvent `json:"statusHistory"`
	RefundProofUrl     *string             `json:"refundProofUrl"`
	PaymentConfirmedAt pgtype.Timestamptz  `json:"paymentConfirmedAt"`
	ID                 uuid.UUID           `json:"id"`
}

// UpdateOrderStatus persists a transition: the new status, the full appended statusHistory,
// and — only when supplied — the denormalized refund_proof_url and payment_confirmed_at
// (COALESCE keeps the existing value when the narg is NULL). The append itself is computed in
// Go by order.Transition; this statement just writes the result in one UPDATE.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus,
		arg.Status,
		arg.StatusHistory,
		arg.RefundProofUrl,
		arg.PaymentConfirmedAt,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Status,
		&i.CustomerID,
		&i.ShippingAddress,
		&i.Subtotal,
		&i.ShippingFee,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentProofUrl,
		&i.PaymentConfirmedAt,
		&i.RefundProofUrl,
		&i.TrackingCode,
		&i.Note,
		&i.StatusHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QcPhotoUrl,
	)
	return i, err
}
