// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (id, aggregate_type, aggregate_id, event_type, payload, dedup_key)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxParams struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregateType"`
	AggregateID   uuid.UUID       `json:"aggregateId"`
	EventType     string          `json:"eventType"`
	Payload       json.RawMessage `json:"payload"`
	DedupKey      string          `json:"dedupKey"`
}

// outbox.sql — the transactional outbox write path (PR-2b). InsertOutbox is the only
// mutation slice 2 performs on this table; the relay's SELECT/mark-published queries land
// in slice 3. seq/status/attempts/created_at use column defaults; published_at stays NULL
// until the relay publishes.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.DedupKey,
	)
	return err
}
