// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const incrementOutboxAttempts = `-- name: IncrementOutboxAttempts :exec
UPDATE outbox SET attempts = attempts + 1
WHERE id = $1
`

// IncrementOutboxAttempts bumps the per-row publish-attempt counter on a poison (per-message
// PubAck rejection). A transient connection/no-stream failure must NOT call this.
func (q *Queries) IncrementOutboxAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOutboxAttempts, id)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (id, aggregate_type, aggregate_id, event_type, payload, dedup_key)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxParams struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregateType"`
	AggregateID   uuid.UUID       `json:"aggregateId"`
	EventType     string          `json:"eventType"`
	Payload       json.RawMessage `json:"payload"`
	DedupKey      string          `json:"dedupKey"`
}

// outbox.sql — the transactional outbox write path (PR-2b) + the slice-3 relay drain path
// (PR-3b). InsertOutbox is the only mutation a domain tx performs; the four relay queries
// below run OUTSIDE any domain tx (the relay reads committed rows only). seq/status/attempts/
// created_at use column defaults; published_at stays NULL until the relay publishes.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.DedupKey,
	)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox SET status = 'failed'
WHERE id = $1
`

// MarkOutboxFailed quarantines a poison row after RelayMaxAttempts so it stops re-poisoning
// the seq scan and blocking later rows (head-of-line). Surfaced in a future Admin view.
func (q *Queries) MarkOutboxFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, id)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET status = 'published', published_at = now()
WHERE id = $1
`

// MarkOutboxPublished flips a row to published ONLY after its JetStream PubAck (ADR-029:
// publish → await PubAck → mark, never mark-then-publish).
func (q *Queries) MarkOutboxPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const selectPendingOutbox = `-- name: SelectPendingOutbox :many
SELECT id, event_type, payload, attempts
FROM outbox
WHERE status = 'pending'
ORDER BY seq
LIMIT $1
`

type SelectPendingOutboxRow struct {
	ID        uuid.UUID       `json:"id"`
	EventType string          `json:"eventType"`
	Payload   json.RawMessage `json:"payload"`
	Attempts  int32           `json:"attempts"`
}

// SelectPendingOutbox scans the WHOLE pending SET in commit order each tick (ADR-029). It
// deliberately scans `status='pending' ORDER BY seq` — NOT a `seq > watermark` cursor and NOT
// `FOR UPDATE SKIP LOCKED`: bigserial `seq` is assigned at INSERT, not COMMIT, so a lower-seq
// tx can become visible AFTER a higher-seq one already published. A watermark would skip that
// late-committing lower-seq row forever = silent money-event loss. Single instance (ADR-009)
// ⇒ no SKIP LOCKED / advisory lock. Uses the partial index outbox_unpublished_idx.
func (q *Queries) SelectPendingOutbox(ctx context.Context, limit int32) ([]SelectPendingOutboxRow, error) {
	rows, err := q.db.Query(ctx, selectPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPendingOutboxRow
	for rows.Next() {
		var i SelectPendingOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
