// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ping.sql

package sqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

// ping.sql — the sqlc pipeline smoke query. It gives `sqlc vet`/`sqlc diff`
// substantive content before the first domain query lands (InsertOutbox, PR-2b) and
// proves codegen end-to-end. Readiness uses pgxpool.Ping directly, not this query.
// (No leading underscore in the filename — Go ignores `_`-prefixed source files.)
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
