// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// outbox.sql — the transactional outbox write path (PR-2b). InsertOutbox is the only
	// mutation slice 2 performs on this table; the relay's SELECT/mark-published queries land
	// in slice 3. seq/status/attempts/created_at use column defaults; published_at stays NULL
	// until the relay publishes.
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	// ping.sql — the sqlc pipeline smoke query. It gives `sqlc vet`/`sqlc diff`
	// substantive content before the first domain query lands (InsertOutbox, PR-2b) and
	// proves codegen end-to-end. Readiness uses pgxpool.Ping directly, not this query.
	// (No leading underscore in the filename — Go ignores `_`-prefixed source files.)
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
