// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getReplyTemplateByID = `-- name: GetReplyTemplateByID :one
SELECT id, title, body, variables, created_at, updated_at FROM reply_templates WHERE id = $1
`

func (q *Queries) GetReplyTemplateByID(ctx context.Context, id uuid.UUID) (ReplyTemplate, error) {
	row := q.db.QueryRow(ctx, getReplyTemplateByID, id)
	var i ReplyTemplate
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one

SELECT id, shop_info, bank_account, shipping_rules, refund_policy, updated_at FROM settings WHERE id = true
`

// settings.sql — config/reference queries (PR-2g): the settings singleton, the append-only
// bank-account audit log, and the extension reply templates. spec.md §02 · conventions.md §57.
//
// bank_account is NOT changed through UpdateSettings — money-out config goes through
// internal/db/settings.go UpdateBankAccountTx, which runs UpdateBankAccount + InsertBankAudit on ONE
// tx so the STK change and its audit row commit together (conventions §57). setting_bank_audit has
// INSERT + SELECT only — no UPDATE/DELETE query exists, and a DB trigger blocks them anyway.
func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ShopInfo,
		&i.BankAccount,
		&i.ShippingRules,
		&i.RefundPolicy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBankAudit = `-- name: InsertBankAudit :one
INSERT INTO setting_bank_audit (id, changed_by, bank_account, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, seq, changed_by, bank_account, reason, created_at
`

type InsertBankAuditParams struct {
	ID          uuid.UUID `json:"id"`
	ChangedBy   uuid.UUID `json:"changedBy"`
	BankAccount []byte    `json:"bankAccount"`
	Reason      *string   `json:"reason"`
}

func (q *Queries) InsertBankAudit(ctx context.Context, arg InsertBankAuditParams) (SettingBankAudit, error) {
	row := q.db.QueryRow(ctx, insertBankAudit,
		arg.ID,
		arg.ChangedBy,
		arg.BankAccount,
		arg.Reason,
	)
	var i SettingBankAudit
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.ChangedBy,
		&i.BankAccount,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertReplyTemplate = `-- name: InsertReplyTemplate :one
INSERT INTO reply_templates (id, title, body, variables)
VALUES ($1, $2, $3, $4)
RETURNING id, title, body, variables, created_at, updated_at
`

type InsertReplyTemplateParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Variables []byte    `json:"variables"`
}

func (q *Queries) InsertReplyTemplate(ctx context.Context, arg InsertReplyTemplateParams) (ReplyTemplate, error) {
	row := q.db.QueryRow(ctx, insertReplyTemplate,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Variables,
	)
	var i ReplyTemplate
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankAudit = `-- name: ListBankAudit :many
SELECT id, seq, changed_by, bank_account, reason, created_at FROM setting_bank_audit ORDER BY seq DESC
`

// ListBankAudit returns the money-out config history, newest first (the owner audit view). Ordering is
// by seq (monotonic insertion order), so it is deterministic even when two changes share a created_at
// microsecond — a random-uuid tiebreaker would not be.
func (q *Queries) ListBankAudit(ctx context.Context) ([]SettingBankAudit, error) {
	rows, err := q.db.Query(ctx, listBankAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettingBankAudit
	for rows.Next() {
		var i SettingBankAudit
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ChangedBy,
			&i.BankAccount,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplyTemplates = `-- name: ListReplyTemplates :many
SELECT id, title, body, variables, created_at, updated_at FROM reply_templates ORDER BY title
`

func (q *Queries) ListReplyTemplates(ctx context.Context) ([]ReplyTemplate, error) {
	rows, err := q.db.Query(ctx, listReplyTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplyTemplate
	for rows.Next() {
		var i ReplyTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccount = `-- name: UpdateBankAccount :one
UPDATE settings
SET bank_account = $1,
    updated_at = now()
WHERE id = true
RETURNING id, shop_info, bank_account, shipping_rules, refund_policy, updated_at
`

// UpdateBankAccount sets the VietQR STK the server renders the static QR from. Called only inside
// UpdateBankAccountTx, alongside InsertBankAudit, so every change is audited (conventions §57).
func (q *Queries) UpdateBankAccount(ctx context.Context, bankAccount []byte) (Setting, error) {
	row := q.db.QueryRow(ctx, updateBankAccount, bankAccount)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ShopInfo,
		&i.BankAccount,
		&i.ShippingRules,
		&i.RefundPolicy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET shop_info = $1,
    shipping_rules = $2,
    refund_policy = $3,
    updated_at = now()
WHERE id = true
RETURNING id, shop_info, bank_account, shipping_rules, refund_policy, updated_at
`

type UpdateSettingsParams struct {
	ShopInfo      []byte `json:"shopInfo"`
	ShippingRules []byte `json:"shippingRules"`
	RefundPolicy  string `json:"refundPolicy"`
}

// UpdateSettings writes the non-money config (shop info, shipping rules, refund policy). It does NOT
// touch bank_account — that goes through the audited UpdateBankAccountTx seam.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.ShopInfo, arg.ShippingRules, arg.RefundPolicy)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ShopInfo,
		&i.BankAccount,
		&i.ShippingRules,
		&i.RefundPolicy,
		&i.UpdatedAt,
	)
	return i, err
}
