// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, role, active, password_hash FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, role, active, password_hash FROM users WHERE id = $1
`

// Resolve a verified JWT's `sub` back to the authoritative user row (PR-3e-2 auth boundary).
// The DB row — not the token claim — is the source of truth for role + active: a token minted
// before a role change or deactivation must not outrank the current record.
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.PasswordHash,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one

INSERT INTO users (id, name, email, role, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, role, active, password_hash
`

type InsertUserParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Email  string    `json:"email"`
	Role   UserRole  `json:"role"`
	Active bool      `json:"active"`
}

// users.sql — staff/owner account queries (PR-2d). spec.md §02 User.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.PasswordHash,
	)
	return i, err
}

const insertUserWithCredential = `-- name: InsertUserWithCredential :one
INSERT INTO users (id, name, email, role, active, password_hash)
VALUES ($1, $2, $3, $4, true, $5)
RETURNING id, name, email, role, active, password_hash
`

type InsertUserWithCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Role         UserRole  `json:"role"`
	PasswordHash *string   `json:"passwordHash"`
}

// Invite a staff/owner account WITH a login credential (P3-q). Unlike InsertUser (attribution-only, no
// password), this sets password_hash so the invitee logs in immediately with the owner-set password.
// active is forced true (an invited account is live). A duplicate email hits the UNIQUE(email) index →
// 23505, surfaced as ErrDuplicate → 409 (Identity.InviteUser). role is validated to {owner,staff} in the
// handler before it reaches the user_role enum.
func (q *Queries) InsertUserWithCredential(ctx context.Context, arg InsertUserWithCredentialParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUserWithCredential,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, role, active, password_hash FROM users ORDER BY role, name
`

// Team roster for the admin staff/roles surface (P3-q). Every account (owner + staff); owner first
// (user_role orders by its declared order, owner < staff), then by name — deterministic, no pagination
// (a made-to-order shop's team is small).
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Active,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOwnerCredential = `-- name: UpsertOwnerCredential :one
INSERT INTO users (id, name, email, role, active, password_hash)
VALUES ($1, $2, $3, 'owner', true, $4)
ON CONFLICT (email) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      role          = 'owner',
      active        = true,
      name          = EXCLUDED.name
RETURNING id, name, email, role, active, password_hash
`

type UpsertOwnerCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash *string   `json:"passwordHash"`
}

// Seed or rotate the first owner's login credential (PR-3e-1, `make seed-owner`). Forces
// role=owner + active=true and is idempotent on the UNIQUE email, so re-running it rotates the
// password hash rather than failing. This is the ONLY writer of password_hash this slice; there
// is no self-service change-password endpoint yet (deferred).
func (q *Queries) UpsertOwnerCredential(ctx context.Context, arg UpsertOwnerCredentialParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertOwnerCredential,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.PasswordHash,
	)
	return i, err
}
