// Codegen for @lumin/api-client: openapi-typescript renders services/core-api/openapi.yaml
// (the single hand-authored wire contract, ADR-031) into src/schema.gen.ts. Run via
// `pnpm --filter @lumin/api-client codegen`. The committed output is the TS half of the
// contract (openapi-fetch consumes the `paths` type); the Go half is oapi-codegen.
//
// This module is BOTH the generator (when run as a script) AND the single source of the
// render logic imported by test/schema.stale.test.ts — so the stale gate regenerates
// through the exact same path and cannot drift from what `codegen` writes.
/* global process, console, URL */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

export const SPEC_URL = new URL('../../../services/core-api/openapi.yaml', import.meta.url);
export const GEN_URL = new URL('../src/schema.gen.ts', import.meta.url);

const HEADER = [
  '// Code generated by openapi-typescript from services/core-api/openapi.yaml. DO NOT EDIT.',
  '// Regenerate: `pnpm --filter @lumin/api-client codegen` (ADR-031 — the YAML is the source of',
  '// truth). packages/api-client/test/schema.stale.test.ts fails if this drifts from a fresh regen.',
  '',
  '',
].join('\n');

export async function renderSchema() {
  const ast = await openapiTS(SPEC_URL);
  return HEADER + astToString(ast);
}

// Only write when invoked directly (`node scripts/codegen.mjs`) — importing this from the
// test must NOT touch the working tree.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(GEN_URL, await renderSchema());
  console.log('wrote packages/api-client/src/schema.gen.ts');
}
