// Code generated by openapi-typescript from services/core-api/openapi.yaml. DO NOT EDIT.
// Regenerate: `pnpm --filter @lumin/api-client codegen` (ADR-031 — the YAML is the source of
// truth). packages/api-client/test/schema.stale.test.ts fails if this drifts from a fresh regen.

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email + password login; sets the session cookie on success.
         * @description Verifies the credential (bcrypt, constant-time) and, on success, mints a signed JWT set as an httpOnly+Secure+SameSite cookie. A uniform error is returned for both unknown email and bad password (no user enumeration). The cookie — not the body — carries the token.
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie. */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an order (web → PENDING_CONFIRM, public; inbox → PAID, staff/owner only).
         * @description Runs behind optional-auth: `channel=web` is public and creates a PENDING_CONFIRM order from a validated `paymentProofUrl`; `channel=inbox` mints a born-PAID order with no payment record and therefore REQUIRES a resolved staff/owner actor (rejected 403 otherwise — conventions §17, ADR-012). Totals are computed server-side; any client `total`/`subtotal`/`unitPrice` is rejected.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance an order's status (RBAC-gated; reconcile→PAID and →REFUNDED are owner-only).
         * @description Applies one OrderStatus transition through the domain guard. The reconcile edge PENDING_CONFIRM→PAID is dispatched to ConfirmPaymentTx (the only `order.paid` emitter); every other edge goes through AdvanceStatusTx. `reason` is required for CANCELLED/REFUNDED; `refundProofUrl` for REFUNDED; `trackingCode` for →SHIPPING. Actor/role/timestamp come from the auth context + server clock, never the body.
         */
        post: operations["transitionOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin dashboard aggregates (counts + net revenue + recent orders + todos).
         * @description Returns raw int-VND amounts, counts, and OrderStatus enums — no server-formatted money, no translated labels (label keys stay i18n, resolved client-side). Net revenue follows spec §04 (PAID/PRINTING/SHIPPING/COMPLETED minus REFUNDED, scoped to the Asia/Ho_Chi_Minh day).
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the settings singleton (admin-gated). */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/bank-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the VietQR STK (owner-only; persisted with an append-only audit row).
         * @description Owner-only (requireOwner). Updates `settings.bank_account` AND appends a setting_bank_audit row in one transaction (UpdateBankAccountTx) — an STK change can never land without its audit trail (conventions §57).
         */
        patch: operations["updateBankAccount"];
        trace?: never;
    };
    "/admin/reply-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the extension reply templates (admin-gated read). */
        get: operations["listReplyTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Order lifecycle status (spec §04). 5 progress milestones + 2 close states.
         * @enum {string}
         */
        OrderStatus: "PENDING_CONFIRM" | "PAID" | "PRINTING" | "SHIPPING" | "COMPLETED" | "CANCELLED" | "REFUNDED";
        /**
         * @description Order origin (spec §04).
         * @enum {string}
         */
        Channel: "web" | "inbox";
        /**
         * @description Actor role for a transition (spec §08). `system` is a runtime-only actor (e.g. delivery auto-complete) — it is NEVER a stored user role; see UserRole.
         * @enum {string}
         */
        Role: "owner" | "staff" | "system";
        /**
         * @description Stored user role (Postgres `user_role`). The subset of Role that a logged-in user can hold — `system` is excluded (a runtime actor, never persisted).
         * @enum {string}
         */
        UserRole: "owner" | "staff";
        /** @description One appended statusHistory record (spec §02/§04). `from` is null only at creation. */
        StatusEvent: {
            from: components["schemas"]["OrderStatus"] | null;
            to: components["schemas"]["OrderStatus"];
            /**
             * Format: date-time
             * @description ISO-8601 UTC, trailing Z (e.g. 2026-06-25T00:00:00.000Z).
             */
            at: string;
            /** @description Actor — a `users.id` for staff/owner, the sentinel "customer" for guest web-create. */
            byUser: string;
            /** @description Required when `to` is CANCELLED or REFUNDED. */
            reason?: string;
            /**
             * Format: uri
             * @description Required when `to` is REFUNDED (transfer-back proof image).
             */
            refundProofUrl?: string;
        };
        /** @description Vietnamese shipping address — no district level (ADR-017). */
        Address: {
            province: string;
            ward: string;
            street: string;
        };
        /** @description Per-item engraving (distinct from a Review's text — that field is `body`). */
        Personalization: {
            text: string;
            zoneId: string;
        };
        Customer: {
            name: string;
            /** @description Vietnamese mobile — `0` or `+84` prefix + 9 digits. */
            phone: string;
            /** Format: email */
            email?: string;
            socialHandle?: string;
        };
        /** @description A priced line item as returned in an Order (unitPrice is server-derived). */
        OrderItem: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            colorId?: string;
            optionIds: string[];
            personalization?: components["schemas"]["Personalization"];
            quantity: number;
            /**
             * Format: int64
             * @description Server-derived int VND (base + color/option deltas). Never accepted from the client.
             */
            unitPrice: number;
        };
        /** @description A requested line item. Deliberately has NO unitPrice — the server re-derives every price from the catalog (always-must #2); a client price is never trusted. */
        OrderItemInput: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            colorId?: string;
            /** @default [] */
            optionIds: string[];
            personalization?: components["schemas"]["Personalization"];
            quantity: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** @description Human order code, e.g. */
            code: string;
            channel: components["schemas"]["Channel"];
            status: components["schemas"]["OrderStatus"];
            customer: components["schemas"]["Customer"];
            shippingAddress: components["schemas"]["Address"];
            items: components["schemas"]["OrderItem"][];
            /** Format: int64 */
            subtotal: number;
            /** Format: int64 */
            shippingFee: number;
            /** Format: int64 */
            total: number;
            /** Format: uri */
            paymentProofUrl?: string;
            /** Format: date-time */
            paymentConfirmedAt?: string;
            /** Format: uri */
            refundProofUrl?: string;
            trackingCode?: string;
            note?: string;
            statusHistory: components["schemas"]["StatusEvent"][];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Order intake, discriminated on `channel`: `web` (public → PENDING_CONFIRM) vs `inbox` (staff/owner-only → PAID). This is a NAMED schema, not an inline oneOf, so oapi-codegen (strict-server) emits a usable discriminated union (AsCreateWebOrderInput / ValueByDiscriminator) instead of an opaque raw-message body the handler cannot read. */
        CreateOrderInput: components["schemas"]["CreateWebOrderInput"] | components["schemas"]["CreateInboxOrderInput"];
        /** @description Public web order → PENDING_CONFIRM. `paymentProofUrl` (the CK receipt image) is required. If any item carries `personalization`, both `personalizationAck` and `engraveEchoConfirmed` MUST be true (the no-return acknowledgement + engrave-echo step, ADR-012) — enforced server-side. */
        CreateWebOrderInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            channel: "web";
            customer: components["schemas"]["Customer"];
            shippingAddress: components["schemas"]["Address"];
            items: components["schemas"]["OrderItemInput"][];
            /** Format: uri */
            paymentProofUrl: string;
            personalizationAck?: boolean;
            engraveEchoConfirmed?: boolean;
        };
        /** @description Staff/owner-created inbox order → born PAID with no payment record (the staff already verified money landed, conventions §17). Requires a resolved staff/owner actor; no `paymentProofUrl`. */
        CreateInboxOrderInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            channel: "inbox";
            customer: components["schemas"]["Customer"];
            shippingAddress: components["schemas"]["Address"];
            items: components["schemas"]["OrderItemInput"][];
            note?: string;
        };
        /** @description One requested status change. `reason` required for CANCELLED/REFUNDED; `refundProofUrl` for REFUNDED; `trackingCode` for →SHIPPING. Actor/role/time are NOT in the body (server-sourced). */
        TransitionRequest: {
            to: components["schemas"]["OrderStatus"];
            reason?: string;
            /** Format: uri */
            refundProofUrl?: string;
            trackingCode?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description The authenticated user (no credential material). */
        AuthUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
        };
        /** @description VietQR STK the server renders the static QR from (conventions §57). May be unset. */
        BankAccount: {
            /** @description Bank BIN (VietQR napas bank id). */
            bin?: string;
            accountNumber?: string;
            accountName?: string;
        };
        /** @description Owner-only STK change (PATCH). `reason` is the optional audit note. */
        BankAccountUpdate: {
            bin: string;
            accountNumber: string;
            accountName: string;
            reason?: string;
        };
        /** @description The settings singleton. `shopInfo` and `shippingRules` are free-form jsonb whose precise shapes are pinned in the Phase-1 storefront slice; typed loosely here on purpose. */
        Settings: {
            shopInfo?: {
                [key: string]: unknown;
            };
            bankAccount: components["schemas"]["BankAccount"];
            shippingRules?: {
                [key: string]: unknown;
            }[];
            refundPolicy: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description An extension reply template (spec §02). */
        ReplyTemplate: {
            /** Format: uuid */
            id: string;
            title: string;
            body: string;
            /** @description Placeholder tokens, e.g. ["{tên}", "{mã đơn}", "{STK}"]. */
            variables: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DashboardSnapshot: {
            stats: components["schemas"]["DashboardStats"];
            recentOrders: components["schemas"]["RecentOrder"][];
            todos: components["schemas"]["DashboardTodos"];
        };
        DashboardStats: {
            newOrdersToday: number;
            /**
             * Format: int64
             * @description Net revenue (int VND) for the Asia/Ho_Chi_Minh day (spec §04).
             */
            revenueToday: number;
            printing: number;
            reviewsWaiting: number;
        };
        RecentOrder: {
            /** Format: uuid */
            id: string;
            code: string;
            customerName: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: int64 */
            total: number;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardTodos: {
            pendingConfirm: number;
            paidWaitingPrint: number;
        };
        /** @description The one error shape every endpoint returns (ADR-032). `code` is a stable machine code (e.g. NOT_FOUND, INVALID_EDGE, RBAC, REASON_REQUIRED, VALIDATION); `messageKey` is a next-intl key (the domain's Vietnamese prose is NEVER forwarded). `fields` maps a field path → messageKey for per-field validation errors. */
        ErrorEnvelope: {
            code: string;
            messageKey: string;
            fields?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Malformed request (bad JSON, missing/invalid field). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed (RBAC). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid state transition (edge not allowed from the current status). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Semantically invalid (e.g. missing reason/refund-proof/tracking-code, empty cart). */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. The session cookie is set via Set-Cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Order created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
        };
    };
    transitionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Transition applied; the updated order is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateBankAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankAccountUpdate"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listReplyTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reply templates, ordered by title. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyTemplate"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
