// Code generated by openapi-typescript from services/core-api/openapi.yaml. DO NOT EDIT.
// Regenerate: `pnpm --filter @lumin/api-client codegen` (ADR-031 — the YAML is the source of
// truth). packages/api-client/test/schema.stale.test.ts fails if this drifts from a fresh regen.

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email + password login; sets the session cookie on success.
         * @description Verifies the credential (bcrypt, constant-time) and, on success, mints a signed JWT set as an httpOnly+Secure+SameSite cookie. A uniform error is returned for both unknown email and bad password (no user enumeration). The cookie — not the body — carries the token.
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie. */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an order (web → PENDING_CONFIRM, public; inbox → PAID, staff/owner only).
         * @description Runs behind optional-auth: `channel=web` is public and creates a PENDING_CONFIRM order from a validated `paymentProofUrl`; `channel=inbox` mints a born-PAID order with no payment record and therefore REQUIRES a resolved staff/owner actor (rejected 403 otherwise — conventions §17, ADR-012). Totals are computed server-side; any client `total`/`subtotal`/`unitPrice` is rejected.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance an order's status (RBAC-gated; reconcile→PAID and →REFUNDED are owner-only).
         * @description Applies one OrderStatus transition through the domain guard. The reconcile edge PENDING_CONFIRM→PAID is dispatched to ConfirmPaymentTx (the only `order.paid` emitter); every other edge goes through AdvanceStatusTx. `reason` is required for CANCELLED/REFUNDED; `refundProofUrl` for REFUNDED; `trackingCode` for →SHIPPING. Actor/role/timestamp come from the auth context + server clock, never the body.
         */
        post: operations["transitionOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public guest order lookup by code + phone — a minimal, non-leaking timeline.
         * @description Public order tracking for a guest who has no account (no auth). BOTH the order code AND the phone used on the order must match; an unknown code and a phone mismatch return the SAME 404 NOT_FOUND (no order-existence enumeration). The phone is compared in constant time and a per-code token-bucket + lockout guards against brute-forcing the phone for a known code (conventions §Bảo mật; the Cloudflare WAF is the per-IP layer). Returns a deliberately minimal PublicOrderTimeline — NEVER the internal Order: no customer PII, address, line items, money, payment/refund proof, internal note, or the statusHistory actor/reason fields (ADR-032). The `phone` param carries NO schema pattern on purpose — a malformed phone must funnel to the same 404, never a 400 (which would be an enumeration signal).
         */
        get: operations["lookupOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public storefront catalog list (active-only) — paginated card projection.
         * @description Public catalog list (no auth). Returns ACTIVE products only as a lightweight card projection (no colors/options/description body → no N+1), paginated and sortable, optionally filtered by category slug. Draft/archived products are NEVER listed (no catalog-existence leak, matching the detail read). Money (basePrice) is raw int-VND; the client formats via @lumin/core (always-must #2). The response carries a weak ETag + a provisional Cache-Control (the storefront ISR/purge strategy is finalized with the frontend PR, P1-f); a matching If-None-Match returns 304. The `q` full-text parameter (P1-e, ADR-016) filters by an accent-insensitive search over the product name/description ("den" matches "đèn"); it is ANDed inside the active-only scope so it never surfaces a hidden product, and the sort/pagination are unchanged (no relevance ranking — small catalog).
         */
        get: operations["getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public storefront product detail (active-only) — product + colors + options.
         * @description Public catalog read (no auth). Returns the ACTIVE product for the slug, bundled with its named print colors and customization options. A draft/archived product OR an unknown slug both return 404 NOT_FOUND — the public surface must not distinguish a hidden product from a missing one (no catalog-existence leak). Money fields (basePrice, colors[].priceDelta, options[].priceDelta) are raw int-VND; the client formats via @lumin/core (always-must #2). No productType in Phase 1 (D-P1-1; Pet Tag activation lands later with its own migration + parity update).
         */
        get: operations["getProductBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public storefront product reviews (published-only) — paginated, newest first.
         * @description Public review list (no auth) for a product, newest first, paginated. Returns ONLY published reviews — the status='published' filter lives at the SQL source, so a moderated-away (hidden) review can NEVER leak (the same non-leak stance as the active-only product reads). An unknown slug OR a draft/archived product both return 404 NOT_FOUND, identical to the detail read (no catalog-existence probe). The reviewer's identity is deliberately NOT exposed (PDPL — reviews carry a nullable customer_id and guests may review; no public PII), so only the review content crosses the wire. The response carries a weak ETag + a provisional Cache-Control (the storefront ISR/purge strategy is finalized with the frontend PR, P1-f), consistent with the /products list; a matching If-None-Match returns 304 with no body. No sort param in Phase 1 (newest first only; an additive `sort` is a later PR if the reviews section design needs it).
         */
        get: operations["getProductReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public storefront category list — the browsable taxonomy for the catalog-browse chips.
         * @description Public category list (no auth). Returns the BROWSABLE category taxonomy (spec §02) A→Z — only categories that contain at least one ACTIVE product. Categories inherit visibility transitively through their products, so a category whose only products are draft/archived is NOT listed (no dead-end chip, and no leak of an unreleased category name — the same non-leak stance as the product reads). It is a small, admin-curated set, so there is no filter or pagination. When no category is browsable the response is an empty array `[]`, NEVER a 404. The response carries a weak ETag + a provisional Cache-Control (the storefront ISR/purge strategy is finalized with the frontend PR, P1-f), consistent with the /products list; a matching If-None-Match returns 304 with no body.
         */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Server-authoritative line/subtotal quote for a selection (no shipping/address).
         * @description Public storefront pricing (no auth). Re-derives each line's unitPrice from the catalog via the same authority gate as checkout — never trusts a client price (always-must #2). Returns per-line unitPrice + lineTotal and the subtotal ONLY: no shipping, address, or tax (those enter at order creation, Phase 2). A non-active or unknown product is 422 PRODUCT_UNAVAILABLE (no catalog-existence leak, matching checkout). Engrave maxChars is enforced server-side by rune count. All money is raw int-VND; the client formats via @lumin/core. The request reuses OrderItemInput, which has no price field, so a client cannot declare a price (schema-level guarantee; unlike checkout this endpoint persists nothing and its response IS the authoritative price, so no loud money-key reject is needed).
         */
        post: operations["quotePrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin dashboard aggregates (counts + net revenue + recent orders + todos).
         * @description Returns raw int-VND amounts, counts, and OrderStatus enums — no server-formatted money, no translated labels (label keys stay i18n, resolved client-side). Net revenue follows spec §04 (PAID/PRINTING/SHIPPING/COMPLETED minus REFUNDED, scoped to the Asia/Ho_Chi_Minh day).
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the settings singleton (admin-gated). */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/bank-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the VietQR STK (owner-only; persisted with an append-only audit row).
         * @description Owner-only (requireOwner). Updates `settings.bank_account` AND appends a setting_bank_audit row in one transaction (UpdateBankAccountTx) — an STK change can never land without its audit trail (conventions §57).
         */
        patch: operations["updateBankAccount"];
        trace?: never;
    };
    "/admin/reply-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the extension reply templates (admin-gated read). */
        get: operations["listReplyTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Order lifecycle status (spec §04). 5 progress milestones + 2 close states.
         * @enum {string}
         */
        OrderStatus: "PENDING_CONFIRM" | "PAID" | "PRINTING" | "SHIPPING" | "COMPLETED" | "CANCELLED" | "REFUNDED";
        /**
         * @description Order origin (spec §04).
         * @enum {string}
         */
        Channel: "web" | "inbox";
        /**
         * @description Actor role for a transition (spec §08). `system` is a runtime-only actor (e.g. delivery auto-complete) — it is NEVER a stored user role; see UserRole.
         * @enum {string}
         */
        Role: "owner" | "staff" | "system";
        /**
         * @description Stored user role (Postgres `user_role`). The subset of Role that a logged-in user can hold — `system` is excluded (a runtime actor, never persisted).
         * @enum {string}
         */
        UserRole: "owner" | "staff";
        /**
         * @description Product lifecycle (spec §02, Postgres `product_status`). The detail read returns `active` only.
         * @enum {string}
         */
        ProductStatus: "active" | "draft" | "archived";
        /**
         * @description Customization option kind (spec §02, Postgres `option_type`). `text` carries an engraving char limit (maxChars).
         * @enum {string}
         */
        OptionType: "text" | "choice";
        /** @description Product bounding size in millimetres (spec §02; displayed "180 × 180 × 240 mm"). */
        Dimensions: {
            /** @description Width in mm. */
            w: number;
            /** @description Depth in mm. */
            d: number;
            /** @description Height in mm. */
            h: number;
        };
        /** @description A named print colour for a product (spec §02). priceDelta is int-VND (may be 0). */
        Color: {
            /** Format: uuid */
            id: string;
            /** @description Display name, e.g. "Kem sữa". */
            name: string;
            /** @description Swatch colour as a hex string. */
            hex: string;
            /** @description Whether the filament is currently in stock. */
            available: boolean;
            /**
             * Format: int64
             * @description Added price in int-VND (>= 0).
             */
            priceDelta: number;
        };
        /** @description A customization option (spec §02). type: text carries an engraving char limit (maxChars). */
        Option: {
            /** Format: uuid */
            id: string;
            label: string;
            description: string;
            type: components["schemas"]["OptionType"];
            /**
             * Format: int64
             * @description Added price in int-VND (>= 0).
             */
            priceDelta: number;
            /** @description Engraving character limit; null unless a limit applies. */
            maxChars?: number | null;
        };
        /** @description Storefront product detail (spec §02). Money fields (basePrice, colors[].priceDelta, options[].priceDelta) are raw int-VND — the client formats via @lumin/core (always-must #2). images[0] is the card cover (sprite-first, ADR-007). No productType in Phase 1 (D-P1-1). */
        Product: {
            /** Format: uuid */
            id: string;
            /** @description Unique URL slug (spec §02). */
            slug: string;
            name: string;
            /** @description Markdown stored as text (spec §02 richtext). */
            description: string;
            /** Format: uuid */
            categoryId: string;
            /**
             * Format: int64
             * @description Starting price in int-VND (>= 0); options may add to it.
             */
            basePrice: number;
            dimensions: components["schemas"]["Dimensions"];
            /** @description Print material (spec §02; open-ended TEXT+CHECK, ADR-028 — not a wire enum). */
            material: string;
            /** @description .glb URL for the on-demand model viewer; empty string when none. */
            model3dUrl: string;
            /** @description Shop photos; images[0] is the card cover (sprite-first, ADR-007). May be empty. */
            images: string[];
            colors: components["schemas"]["Color"][];
            options: components["schemas"]["Option"][];
            status: components["schemas"]["ProductStatus"];
            /**
             * Format: float
             * @description Denormalized average rating; null until the first review.
             */
            ratingAvg?: number | null;
            /** @description Denormalized review count (spec §02). */
            reviewCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Lightweight catalog-list projection of a product (spec §02) — the fields a grid card needs, WITHOUT colors/options/description body (the list avoids the per-product reads the detail read makes → no N+1). basePrice is raw int-VND; images[0] is the card cover (sprite-first, ADR-007). Only ACTIVE products are ever listed, so status is implied and omitted. */
        ProductCard: {
            /** Format: uuid */
            id: string;
            /** @description Unique URL slug (spec §02). */
            slug: string;
            name: string;
            /**
             * Format: int64
             * @description Starting price in int-VND (>= 0).
             */
            basePrice: number;
            /** Format: uuid */
            categoryId: string;
            /** @description Shop photos; images[0] is the card cover (ADR-007). May be empty. */
            images: string[];
            /**
             * Format: float
             * @description Denormalized average rating; null until the first review.
             */
            ratingAvg?: number | null;
            /** @description Denormalized review count (spec §02). */
            reviewCount: number;
        };
        /** @description One page of catalog cards plus the pagination envelope (spec §03 list state). `total` is the count of active products matching the filter across all pages; the client derives the page count. */
        ProductList: {
            items: components["schemas"]["ProductCard"][];
            /** @description 1-based page number echoed from the request. */
            page: number;
            /** @description Items per page echoed from the request. */
            pageSize: number;
            /** @description Total active products matching the filter, across all pages. */
            total: number;
        };
        /** @description One PUBLISHED product review as it crosses the public wire (spec §02). The author's identity is deliberately omitted — reviews carry a nullable customer_id and guests may review, so exposing a reviewer name would be public PII (PDPL); only the review content is returned. `reply` is the shop's public reply, null until the shop replies (no Phase-1 write path populates it yet). Hidden reviews are filtered at the SQL source and never appear here. */
        Review: {
            /** Format: uuid */
            id: string;
            /** @description Star rating 1–5 (spec §02). */
            rating: number;
            /** @description The review text (may be empty). */
            body: string;
            /** @description Reviewer photos (spec §02). May be empty. */
            images: string[];
            /** @description The shop's public reply, or null until the shop has replied. */
            reply?: components["schemas"]["ReviewReply"] | null;
            /**
             * Format: date-time
             * @description ISO-8601 UTC when the review was posted.
             */
            createdAt: string;
        };
        /** @description The shop's public reply to a review (spec §02 `reply?`). Null on the parent until replied. */
        ReviewReply: {
            /** @description The shop reply text. */
            body: string;
            /**
             * Format: date-time
             * @description ISO-8601 UTC when the reply was posted.
             */
            at: string;
        };
        /** @description One page of published reviews plus the pagination envelope (spec §03 list state). `total` is the count of PUBLISHED reviews for the product across all pages; the client derives the page count. */
        ReviewList: {
            items: components["schemas"]["Review"][];
            /** @description 1-based page number echoed from the request. */
            page: number;
            /** @description Items per page echoed from the request. */
            pageSize: number;
            /** @description Total published reviews for the product, across all pages. */
            total: number;
        };
        /** @description A catalog category (spec §02) — the taxonomy a product belongs to (Product.categoryId references Category.id) and the storefront browse chips render. No visibility axis: every category is public. */
        Category: {
            /** Format: uuid */
            id: string;
            /** @description Unique URL slug — the value passed to GET /products?category={slug}. */
            slug: string;
            /** @description Human-friendly display name (sentence case). */
            name: string;
        };
        /** @description One appended statusHistory record (spec §02/§04). `from` is null only at creation. */
        StatusEvent: {
            from: components["schemas"]["OrderStatus"] | null;
            to: components["schemas"]["OrderStatus"];
            /**
             * Format: date-time
             * @description ISO-8601 UTC, trailing Z (e.g. 2026-06-25T00:00:00.000Z).
             */
            at: string;
            /** @description Actor — a `users.id` for staff/owner, the sentinel "customer" for guest web-create. */
            byUser: string;
            /** @description Required when `to` is CANCELLED or REFUNDED. */
            reason?: string;
            /**
             * Format: uri
             * @description Required when `to` is REFUNDED (transfer-back proof image).
             */
            refundProofUrl?: string;
        };
        /** @description Vietnamese shipping address — no district level (ADR-017). */
        Address: {
            province: string;
            ward: string;
            street: string;
        };
        /** @description Per-item engraving (distinct from a Review's text — that field is `body`). */
        Personalization: {
            text: string;
            zoneId: string;
        };
        Customer: {
            name: string;
            /** @description Vietnamese mobile — `0` or `+84` prefix + 9 digits. */
            phone: string;
            /** Format: email */
            email?: string;
            socialHandle?: string;
        };
        /** @description A priced line item as returned in an Order (unitPrice is server-derived). */
        OrderItem: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            colorId?: string;
            optionIds: string[];
            personalization?: components["schemas"]["Personalization"];
            quantity: number;
            /**
             * Format: int64
             * @description Server-derived int VND (base + color/option deltas). Never accepted from the client.
             */
            unitPrice: number;
        };
        /** @description A requested line item. Deliberately has NO unitPrice — the server re-derives every price from the catalog (always-must #2); a client price is never trusted. */
        OrderItemInput: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            colorId?: string;
            /** @default [] */
            optionIds: string[];
            personalization?: components["schemas"]["Personalization"];
            quantity: number;
        };
        /** @description One or more selections to price. Reuses OrderItemInput (which has NO unitPrice — the server re-derives every price from the catalog). Returns line/subtotal only; carries no address/shipping. Capped at 50 items: this is a public, unauthenticated read (no rate limit until the edge WAF), and each line costs a catalog round-trip, so the cap bounds the per-request work. */
        PriceQuoteInput: {
            items: components["schemas"]["OrderItemInput"][];
        };
        /** @description Server-computed line prices + subtotal (raw int-VND; no shipping/tax). `lines` is positionally aligned with the request `items` (same index) — a line carries no product reference, so a client maps a line back to its selection by array index. */
        PriceQuote: {
            lines: components["schemas"]["PriceQuoteLine"][];
            /**
             * Format: int64
             * @description Sum of line totals, raw int VND. No shipping/tax (added at order creation, Phase 2).
             */
            subtotal: number;
        };
        /** @description One priced line, positionally aligned with the request item at the same index. Carries the server-derived unit price, its quantity, and the line total — no product ref (map back by index). */
        PriceQuoteLine: {
            /**
             * Format: int64
             * @description Server-derived int VND (base + color delta + Σ option deltas). Never accepted from the client.
             */
            unitPrice: number;
            quantity: number;
            /**
             * Format: int64
             * @description unitPrice × quantity, overflow-checked server-side.
             */
            lineTotal: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** @description Human order code, e.g. */
            code: string;
            channel: components["schemas"]["Channel"];
            status: components["schemas"]["OrderStatus"];
            customer: components["schemas"]["Customer"];
            shippingAddress: components["schemas"]["Address"];
            items: components["schemas"]["OrderItem"][];
            /** Format: int64 */
            subtotal: number;
            /** Format: int64 */
            shippingFee: number;
            /** Format: int64 */
            total: number;
            /** Format: uri */
            paymentProofUrl?: string;
            /** Format: date-time */
            paymentConfirmedAt?: string;
            /** Format: uri */
            refundProofUrl?: string;
            trackingCode?: string;
            note?: string;
            statusHistory: components["schemas"]["StatusEvent"][];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Order intake, discriminated on `channel`: `web` (public → PENDING_CONFIRM) vs `inbox` (staff/owner-only → PAID). This is a NAMED schema, not an inline oneOf, so oapi-codegen (strict-server) emits a usable discriminated union (AsCreateWebOrderInput / ValueByDiscriminator) instead of an opaque raw-message body the handler cannot read. */
        CreateOrderInput: components["schemas"]["CreateWebOrderInput"] | components["schemas"]["CreateInboxOrderInput"];
        /** @description Public web order → PENDING_CONFIRM. `paymentProofUrl` (the CK receipt image) is required. If any item carries `personalization`, both `personalizationAck` and `engraveEchoConfirmed` MUST be true (the no-return acknowledgement + engrave-echo step, ADR-012) — enforced server-side. */
        CreateWebOrderInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            channel: "web";
            customer: components["schemas"]["Customer"];
            shippingAddress: components["schemas"]["Address"];
            items: components["schemas"]["OrderItemInput"][];
            /** Format: uri */
            paymentProofUrl: string;
            personalizationAck?: boolean;
            engraveEchoConfirmed?: boolean;
        };
        /** @description Staff/owner-created inbox order → born PAID with no payment record (the staff already verified money landed, conventions §17). Requires a resolved staff/owner actor; no `paymentProofUrl`. */
        CreateInboxOrderInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            channel: "inbox";
            customer: components["schemas"]["Customer"];
            shippingAddress: components["schemas"]["Address"];
            items: components["schemas"]["OrderItemInput"][];
            note?: string;
        };
        /** @description One requested status change. `reason` required for CANCELLED/REFUNDED; `refundProofUrl` for REFUNDED; `trackingCode` for →SHIPPING. Actor/role/time are NOT in the body (server-sourced). */
        TransitionRequest: {
            to: components["schemas"]["OrderStatus"];
            reason?: string;
            /** Format: uri */
            refundProofUrl?: string;
            trackingCode?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description The authenticated user (no credential material). */
        AuthUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
        };
        /** @description VietQR STK the server renders the static QR from (conventions §57). May be unset. */
        BankAccount: {
            /** @description Bank BIN (VietQR napas bank id). */
            bin?: string;
            accountNumber?: string;
            accountName?: string;
        };
        /** @description Owner-only STK change (PATCH). `reason` is the optional audit note. */
        BankAccountUpdate: {
            bin: string;
            accountNumber: string;
            accountName: string;
            reason?: string;
        };
        /** @description The settings singleton. `shopInfo` and `shippingRules` are free-form jsonb whose precise shapes are pinned in the Phase-1 storefront slice; typed loosely here on purpose. */
        Settings: {
            shopInfo?: {
                [key: string]: unknown;
            };
            bankAccount: components["schemas"]["BankAccount"];
            shippingRules?: {
                [key: string]: unknown;
            }[];
            refundPolicy: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description An extension reply template (spec §02). */
        ReplyTemplate: {
            /** Format: uuid */
            id: string;
            title: string;
            body: string;
            /** @description Placeholder tokens, e.g. ["{tên}", "{mã đơn}", "{STK}"]. */
            variables: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DashboardSnapshot: {
            stats: components["schemas"]["DashboardStats"];
            recentOrders: components["schemas"]["RecentOrder"][];
            todos: components["schemas"]["DashboardTodos"];
        };
        DashboardStats: {
            newOrdersToday: number;
            /**
             * Format: int64
             * @description Net revenue (int VND) for the Asia/Ho_Chi_Minh day (spec §04).
             */
            revenueToday: number;
            printing: number;
            reviewsWaiting: number;
        };
        RecentOrder: {
            /** Format: uuid */
            id: string;
            code: string;
            customerName: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: int64 */
            total: number;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardTodos: {
            pendingConfirm: number;
            paidWaitingPrint: number;
        };
        /** @description The guest-facing order timeline returned by GET /orders/lookup. It is a SEPARATE schema from Order (never a $ref) and exposes ONLY what a customer who already knows their code + phone may see: the code they typed, the current status, a status→time milestone list, an optional carrier tracking code, and the creation instant. It deliberately OMITS every internal field — customer PII, shipping address, line items, money (subtotal/shippingFee/total/unitPrice), payment/refund proof URLs, the internal note, the order uuid, the channel, and the statusHistory actor (byUser) + reason (ADR-032 non-leak). */
        PublicOrderTimeline: {
            /** @description The human order code the guest supplied (e.g. "#LMN-1000"). */
            code: string;
            status: components["schemas"]["OrderStatus"];
            /** @description Reached statuses with the instant each was entered, oldest-first — the progress milestones plus any CANCELLED/REFUNDED close state. The frontend (P1-o) renders labels and shows the close states apart from the 5-step progress track (spec §04). */
            milestones: components["schemas"]["OrderMilestone"][];
            /** @description Carrier waybill, present only from SHIPPING onward (spec §04). Omitted before then. */
            trackingCode?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description One reached order status with the instant it was entered — a whitelist projection of a statusHistory event that drops the actor (byUser), reason, and proof fields (ADR-032 non-leak). */
        OrderMilestone: {
            status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            at: string;
        };
        /** @description The one error shape every endpoint returns (ADR-032). `code` is a stable machine code (e.g. NOT_FOUND, INVALID_EDGE, RBAC, REASON_REQUIRED, VALIDATION); `messageKey` is a next-intl key (the domain's Vietnamese prose is NEVER forwarded). `fields` maps a field path → messageKey for per-field validation errors. */
        ErrorEnvelope: {
            code: string;
            messageKey: string;
            fields?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Malformed request (bad JSON, missing/invalid field). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed (RBAC). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid state transition (edge not allowed from the current status). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Semantically invalid (e.g. missing reason/refund-proof/tracking-code, empty cart). */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limit or lockout tripped (RATE_LIMITED) — too many lookup attempts for this order code. The client should back off (P1-o auto-poll respects this). No Retry-After is exposed so the exact lockout window is not leaked. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. The session cookie is set via Set-Cookie. */
            200: {
                headers: {
                    /** @description Signed JWT in an httpOnly + Secure + SameSite=Strict session cookie (the token is not in the body). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    /** @description Expires the session cookie immediately (logout). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Order created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
        };
    };
    transitionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Transition applied; the updated order is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    lookupOrder: {
        parameters: {
            query: {
                /** @description The order code shown at checkout (e.g. "#LMN-1000"). */
                code: string;
                /** @description The phone number used on the order. No format constraint — a mismatch (or malformed value) returns the uniform 404, never a 400. */
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The code + phone matched; the public order timeline is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrderTimeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getProducts: {
        parameters: {
            query?: {
                /** @description Filter by category slug (spec §02). An unknown slug yields an empty page, not a 404. */
                category?: string;
                /** @description Sort order. Default `newest` (created_at desc, id desc tiebreak for stable paging). */
                sort?: "newest" | "price_asc" | "price_desc" | "rating";
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. Capped at 48 to bound the query on this public, unauthenticated endpoint. */
                pageSize?: number;
                /** @description Full-text search term (accent-insensitive, ADR-016) over the product name/description. Filters within the active-only + category scope; an empty/whitespace value means "no search" (the full catalog). Bounded to 100 characters on this public endpoint (over-length → 400). */
                q?: string;
            };
            header?: {
                /** @description Conditional GET — when it matches the current ETag the server returns 304 with no body. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of active product cards. */
            200: {
                headers: {
                    /** @description Weak validator over the response body; echo it in If-None-Match to revalidate. */
                    ETag?: string;
                    /** @description Public cache directive (provisional — the ISR/purge strategy is finalized in P1-f). */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Not Modified — the client's If-None-Match matched the current ETag. */
            304: {
                headers: {
                    /** @description The current weak validator (unchanged). */
                    ETag?: string;
                    /** @description Public cache directive (provisional — finalized in P1-f). */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getProductBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL slug of the product (spec §02, unique). */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active product with its colors and options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProductReviews: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. Capped at 48 to bound the query on this public, unauthenticated endpoint. */
                pageSize?: number;
            };
            header?: {
                /** @description Conditional GET — when it matches the current ETag the server returns 304 with no body. */
                "If-None-Match"?: string;
            };
            path: {
                /** @description URL slug of the product (spec §02, unique). */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of published reviews for the product (newest first). */
            200: {
                headers: {
                    /** @description Weak validator over the response body; echo it in If-None-Match to revalidate. */
                    ETag?: string;
                    /** @description Public cache directive (provisional — the ISR/purge strategy is finalized in P1-f). */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewList"];
                };
            };
            /** @description Not Modified — the client's If-None-Match matched the current ETag. */
            304: {
                headers: {
                    /** @description The current weak validator (unchanged). */
                    ETag?: string;
                    /** @description Public cache directive (provisional — finalized in P1-f). */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: {
                /** @description Conditional GET — when it matches the current ETag the server returns 304 with no body. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full category taxonomy (may be empty). */
            200: {
                headers: {
                    /** @description Weak validator over the response body; echo it in If-None-Match to revalidate. */
                    ETag?: string;
                    /** @description Public cache directive (provisional — the ISR/purge strategy is finalized in P1-f). */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            /** @description Not Modified — the client's If-None-Match matched the current ETag. */
            304: {
                headers: {
                    /** @description The current weak validator (unchanged). */
                    ETag?: string;
                    /** @description Public cache directive (provisional — finalized in P1-f). */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    quotePrice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceQuoteInput"];
            };
        };
        responses: {
            /** @description The computed line prices and subtotal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceQuote"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateBankAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankAccountUpdate"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listReplyTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reply templates, ordered by title. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyTemplate"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
